Litchi: main.c File Reference
main.c File Reference
#include <include/x86.h>
#include <include/elf.h>
Macros
#define ELFHDR ((struct Elf *) 0x20000)
#define SECTSIZE 512
Functions
void bootmain (void)
void readsect (void *, uint32_t)
void readseg (uint32_t, uint32_t, uint32_t)
void waitdisk (void)
Macro Definition Documentation
ELFHDR
#define ELFHDR ((struct Elf *) 0x20000)
Definition at line 35 of file main.c.
SECTSIZE
#define SECTSIZE 512
Definition at line 34 of file main.c.
Function Documentation
bootmain()
void bootmain (void)
Definition at line 42 of file main.c.
                {
     struct Proghdr *ph, *eph;
     // read 1st page off disk into scratch space to get the header
     readseg((uint32_t) ELFHDR, SECTSIZE * 8, 0);
     // is this a valid ELF?
     if (ELFHDR->e_magic != ELF_MAGIC)
         goto bad;
     // load each program segment (ignores ph flags)
     ph = (struct Proghdr *) ((uint8_t *) ELFHDR + ELFHDR->e_phoff);
     eph = ph + ELFHDR->e_phnum;
     for (; ph < eph; ph++)
         // p_pa is the load address of this segment (as well
         // as the physical address)
         readseg(ph->p_pa, ph->p_memsz, ph->p_offset);
     // call the entry point from the ELF header
     // note: does not return!
     *(uint16_t *) 0xb809e = 0x0a4c;
     ((void (*)(void)) (ELFHDR->e_entry))();
     bad:
     *(uint16_t *) 0xb809e = 0x0c4c;
     // BUGENC: bochs breakpoint port
     outw(0x8A00, 0x8A00);
     outw(0x8A00, 0x8E00);
     while (1)
         /* do nothing */;
 }
readsect()
void readsect (void * dst, uint32_t offset)
Definition at line 113 of file main.c.
{
     // wait for disk to be ready
     waitdisk();
     outb(0x1F2, 1);        // count = 1
     outb(0x1F3, offset);
     outb(0x1F4, offset >> 8);
     outb(0x1F5, offset >> 16);
     outb(0x1F6, (offset >> 24) | 0xE0);
     outb(0x1F7, 0x20);    // cmd 0x20 - read sectors
     // wait for disk to be ready
     waitdisk();
     // read a sector
     insl(0x1F0, dst, SECTSIZE / 4);
 }
Referenced by readseg().
readseg()
void readseg (uint32_t pa, uint32_t count, uint32_t offset)
Definition at line 77 of file main.c.
{
     uint16_t *statusPos = (uint16_t *) 0xb80a0;
     uint32_t end_pa;
     end_pa = pa + count;
     // round down to sector boundary
     pa &= ~(SECTSIZE - 1);
     // translate from bytes to sectors, and kernel starts at sector 1
     offset = (offset / SECTSIZE) + 1;
     // If this is too slow, we could read lots of sectors at a time.
     // We'd write more to memory than asked, but it doesn't matter --
     // we load in increasing order.
     while (pa < end_pa) {
         // Since we haven't enabled paging yet and we're using
         // an identity segment mapping (see boot.S), we can
         // use physical addresses directly.  This won't be the
         // case once JOS enables the MMU.
         readsect((uint8_t *) pa, offset);
         *(statusPos++) = 0x072e;
         pa += SECTSIZE;
         offset++;
     }
 }
Referenced by bootmain().
waitdisk()
void waitdisk (void)
Definition at line 105 of file main.c.
                {
     // wait for disk ready
     // floppy will be stuck here
     while ((inb(0x1F7) & 0xC0) != 0x40)
         /* do nothing */;
 }
Referenced by readsect().