Litchi: mem Namespace Reference
mem Namespace Reference
Functions
void clear (void *dest, size_t count)
int cmp (const void *lhs, const void *rhs, size_t count)
void * copy (void *dest, const void *src, size_t count)
void * move (void *dest, const void *src, size_t count)
void * set (void *dest, uint8_t val, size_t count)
Function Documentation
clear()
void mem::clear (void * dest, size_t count)
Definition at line 88 of file string.cc.
{
         set(dest, 0, count);
     }
Referenced by vmem::pgdir::alloc(), vmem::PageInfo::alloc(), task::allocArray(), trap::Frame::clear(), vmem::pgdir::findPte(), and vmem::page::init().
cmp()
int mem::cmp (const void * lhs, const void * rhs, size_t count)
Definition at line 92 of file string.cc.
{
         auto _lhs = (const char *) lhs;
         auto _rhs = (const char *) rhs;
         while (count--) {
             if (*_lhs == *_rhs) _lhs++, _rhs++;
             else return *_lhs - *_rhs;
         }
         return 0;
     }
Referenced by mp::init(), and mp::searchFP().
copy()
void * mem::copy (void * dest, const void * src, size_t count)
Definition at line 20 of file string.cc.
{
         uint8_t *_dest = (uint8_t *) dest;
         uint8_t *_src = (uint8_t *) src;
         while (count--)
             *(_dest++) = *(_src++);
         return dest;
     }
Referenced by mp::init(), task::Task::loadElf(), move(), console::cga::putChar(), and task::Task::setupMemory().
move()
void * mem::move (void * dest, const void * src, size_t count)
Definition at line 28 of file string.cc.
{
         // https://www.student.cs.uwaterloo.ca/~cs350/common/os161-src-html/doxygen/html/memmove_8c_source.html
         size_t i;
         /*
         * If the buffers don't overlap, it doesn't matter what direction
         * we copy in. If they do, it does, so just assume they always do.
         * We don't concern ourselves with the possibility that the region
         * to copy might roll over across the top of memory, because it's
         * not going to happen.
         *
         * If the destination is above the source, we have to copy
         * back to front to avoid overwriting the data we want to
         * copy.
         *
         *      dest:       dddddddd
         *      src:    ssssssss   ^
         *              |   ^  |___|
         *              |___|
         *
         * If the destination is below the source, we have to copy
         * front to back.
         *
         *      dest:   dddddddd
         *      src:    ^   ssssssss
         *              |___|  ^   |
         *                     |___|
         */
         if ((uintptr_t) dest < (uintptr_t) src) {
             /*
             * As author/maintainer of libc, take advantage of the
             * fact that we know memcpy copies forwards.
             */
             return mem::copy(dest, src, count);
         }
         /*
         * Copy by words in the common case. Look in memcpy.c for more
         * information.
         */
         if ((uintptr_t) dest % sizeof(long) == 0 &&
             (uintptr_t) src % sizeof(long) == 0 &&
             count % sizeof(long) == 0) {
             long *d = static_cast<long *>(dest);
             const long *s = static_cast<const long *>(src);
             /*
             * The reason we copy index i-1 and test i>0 is that
             * i is unsigned -- so testing i>=0 doesn't work.
             */
             for (i = count / sizeof(long); i > 0; i--) {
                 d[i - 1] = s[i - 1];
             }
         } else {
             char *d = static_cast<char *>(dest);
             const char *s = static_cast<const char *>(src);
             for (i = count; i > 0; i--) {
                 d[i - 1] = s[i - 1];
             }
         }
         return dest;
     }
Referenced by __builtin_memmove().
set()
void * mem::set (void * dest, uint8_t val, size_t count)
Definition at line 13 of file string.cc.
{
         uint8_t *_dest = (uint8_t *) dest;
         while (count--)
             *(_dest++) = val;
         return dest;
     }
Referenced by clear(), i386InitLitchi(), and vmem::pgdir::init().