Litchi: vmem::utils Namespace Reference
vmem::utils Namespace Reference
Functions
void dumpP (pte_t *pageDir, physaddr_t beginP, physaddr_t endP)
void dumpV (pte_t *pageDir, void *beginV, void *endV)
char * flagStr (pte_t *entry, char *buf)
void show (pte_t *pageDir, void *beginV, void *endV)
Function Documentation
dumpP()
void vmem::utils::dumpP (pte_t * pageDir, physaddr_t beginP, physaddr_t endP)
Definition at line 417 of file vmem.cc.
{
         using namespace console;
         beginP = ROUNDDOWN(beginP, 16);
         endP = ROUNDUP(endP, 16);
         const size_t _totalMem = totalMem * 1024u;
         out::print("PHYSICAL  0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F\n");
         for (physaddr_t row = beginP; row <= endP; row = (physaddr_t) ((uintptr_t) row + 16)) {
             out::print("%p", row);
             for (physaddr_t pa = row; pa <= row + 15; ++pa) {
                 if (pa >= _totalMem) {
                     err::print("  <INVALID>\n");
                     return;
                 }
                 out::print(" %02X", (uint32_t) (*(uint8_t *) KERN_ADDR(pa)));
             }
             out::print("\n");
         }
     }
Referenced by monitor::vmdumpp().
dumpV()
void vmem::utils::dumpV (pte_t * pageDir, void * beginV, void * endV)
Definition at line 395 of file vmem.cc.
{
         beginV = ROUNDDOWN(beginV, 16);
         endV = ROUNDUP(endV, 16);
         console::out::print("VIRTUAL   0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F\n");
         for (void *row = beginV; row <= endV; row = (void *) ((uintptr_t) row + 16)) {
             console::out::print("%p", row);
             pte_t *pte = pgdir::findPte(pageDir, row, 0);
             if (pte == nullptr) {
                 console::err::print("  <INVALID>\n");
                 return;
             } else if (!(*pte & PTE_P)) {
                 console::err::print("  <NOT PRESENT>\n");
                 return;
             }
             for (uint8_t *va = static_cast<uint8_t *>(row); (void *) va <= (void *) ((uintptr_t) row + 15); ++va) {
                 console::out::print(" %02X", (uint32_t) *va);
             }
             console::out::print("\n");
         }
     }
Referenced by monitor::vmdumpv().
flagStr()
char * vmem::utils::flagStr (pte_t * entry, char * buf)
Definition at line 437 of file vmem.cc.
{
         if (entry == nullptr) return nullptr;
         static const char *str[] = {"_________SR_", "AVLGPDACTUWP"};
         int i;
         for (i = 0; i < 12; ++i) {
             buf[i] = str[((*entry) >> (11 - i)) & 0x1][i];
         }
         buf[i] = '\0';
         return buf;
     }
Referenced by show().
show()
void vmem::utils::show (pte_t * pageDir, void * beginV, void * endV)
Definition at line 374 of file vmem.cc.
{
         beginV = ROUNDDOWN(beginV, PGSIZE);
         endV = ROUNDDOWN(endV, PGSIZE);
         char flagsBuf[13];
         console::out::print("VIRTUAL     PHYSICAL  RC  FLAGS\n");
         for (uintptr_t va = (uintptr_t) beginV; va <= (uintptr_t) endV; va += PGSIZE) {
             console::out::print("%p -> ", va);
             pte_t *pte = pgdir::findPte(pageDir, (void *) va, 0);
             if (pte == nullptr) console::err::print("<NOT MAPPED>\n");
             else {
                 physaddr_t phy = PTE_ADDR(*pte);
                 if (PGNUM(phy) >= nPages)
                     console::err::print("<NOT EXIST>\n");
                 else
                     console::out::print("%p  %2d  %s\n", phy, PageInfo::fromPhy(phy)->refCount,
                                         flagStr(pte, flagsBuf));
             }
         }
     }
Referenced by monitor::vmshow().