Litchi: console::out Namespace Reference
console::out Namespace Reference
Functions
int print (const char *fmt,...)
int printVa (const char *fmt, va_list ap)
void putChar (int c)
Function Documentation
print()
int console::out::print (const char * fmt, ...)
Definition at line 26 of file kernel/printf.cc.
{
             va_list ap;
             va_start(ap, fmt);
             int cnt = printVa(fmt, ap);
             va_end(ap);
             return cnt;
         }
Referenced by task::Task::alloc(), sys::cpuInfo(), task::Task::create(), trap::handler::debug(), task::Task::destroy(), trap::Frame::dispatch(), vmem::utils::dumpP(), vmem::utils::dumpV(), monitor::echo(), task::Task::free(), monitor::help(), i386InitLitchi(), mp::init(), task::init(), trap::init(), vmem::init(), task::Task::loadElf(), main(), monitor::main(), monitor::page(), trap::handler::pageFault(), pageFault2(), pageFault3(), ksyscall::putString(), task::Task::run(), mp::searchFP(), vmem::utils::show(), trap::trap(), and monitor::uname().
printVa()
int console::out::printVa (const char * fmt, va_list ap)
Definition at line 14 of file kernel/printf.cc.
{
             int cnt = 0;
             auto putChar = [&cnt](int c) {
                 out::putChar(c);
                 if (c & 0x00ff) cnt++;
             };
             ge::printFmtVa(putChar, fmt, ap, DEF_FORE, DEF_BACK);
             return cnt;
         }
Referenced by consoleOutPrintC(), print(), and console::in::readlineVa().
putChar()
void console::out::putChar (int c)
Definition at line 225 of file console.cc.
{
             cga::putChar(c, DEF_FORE, DEF_BACK);
             serial::putChar(c, DEF_FORE, DEF_BACK);
         }
Referenced by console::ge::printFmt(), console::ge::printFmtVa(), console::ge::printNumber(), printVa(), console::err::printVa(), ksyscall::putChar(), ksyscall::putString(), and console::in::readlineVa().