Litchi: console::cga Namespace Reference
console::cga Namespace Reference
Functions
static void clear (void)
static void clear (void)
static void cursorRefresh (void)
static void init (void)
static void init (void)
static void putChar (int c, enum color_t defForeColor, enum color_t defBackColor)
static void putChar (int c, enum color_t defForeColor, enum color_t defBackColor)
Variables
static unsigned addr_6845
static uint16_t * buffer
static uint16_t pos
Function Documentation
clear() [1/2]
static void console::cga::clear (void) static
Definition at line 199 of file console.cc.
{
             for (int i = 0; i < CRT_SIZE; ++i) {
                 buffer[i] = (DEF_FORE << 8) | ' ';
             }
             pos = 0;
             cursorRefresh();
         }
Referenced by console::clear().
clear() [2/2]
static void console::cga::clear (void) static
cursorRefresh()
static void console::cga::cursorRefresh (void) inline static
Definition at line 148 of file console.cc.
{
             x86::outb(addr_6845, 14);
             x86::outb(addr_6845 + 1, pos >> 8);
             x86::outb(addr_6845, 15);
             x86::outb(addr_6845 + 1, pos);
         }
Referenced by clear(), and putChar().
init() [1/2]
static void console::cga::init (void) static
Definition at line 121 of file console.cc.
{
             volatile uint16_t *cp;
             uint16_t was;
             unsigned npos;
             cp = (uint16_t *) (KERNBASE + CGA_BUF);
             was = *cp;
             *cp = (uint16_t) 0xA55A;
             if (*cp != 0xA55A) {
                 cp = (uint16_t *) (KERNBASE + MONO_BUF);
                 addr_6845 = MONO_BASE;
             } else {
                 *cp = was;
                 addr_6845 = CGA_BASE;
             }
             // Get cursor position
             x86::outb(addr_6845, 14);
             npos = x86::inb(addr_6845 + 1) << 8;
             x86::outb(addr_6845, 15);
             npos |= x86::inb(addr_6845 + 1);
             buffer = (uint16_t *) cp;
             pos = npos;
         }
Referenced by console::init().
init() [2/2]
static void console::cga::init (void) static
putChar() [1/2]
static void console::cga::putChar (int c, enum color_t defForeColor, enum color_t defBackColor) static
Definition at line 156 of file console.cc.
{
             if ((c & 0xff00) == 0) // no color in c
                 c = COLOR_CHAR(c, defForeColor, defBackColor);
             // Print the character
             switch (c & 0xff) {
                 case '\b':
                     if (pos > 0) buffer[--pos] = (c & ~0xff) | ' ';
                     break;
                 case '\t':
                     putChar(' ', defForeColor, defBackColor);
                     putChar(' ', defForeColor, defBackColor);
                     putChar(' ', defForeColor, defBackColor);
                     putChar(' ', defForeColor, defBackColor);
                     break;
                 case '\n':
                     pos += CRT_COLS;
                     // LF only
                 case '\r':
                     pos = pos / CRT_COLS * CRT_COLS;
                     break;
                 case '\0':
                     break;
                 default:
                     buffer[pos++] = c;
             }
             // Scroll the screen
             if (pos == CRT_SIZE) {
                 for (int i = 0; i < CRT_ROWS - 1; ++i) {
                     mem::copy(buffer + i * CRT_COLS, buffer + (i + 1) * CRT_COLS, CRT_COLS * sizeof(uint16_t));
                 }
                 for (int j = CRT_SIZE - CRT_COLS; j < CRT_SIZE; ++j) {
                     buffer[j] = (c & ~0xff) | ' ';
                 }
                 pos -= CRT_COLS;
             }
             // Move the cursor
             cursorRefresh();
         }
Referenced by console::out::putChar().
putChar() [2/2]
static void console::cga::putChar (int c, enum color_t defForeColor, enum color_t defBackColor) static
Variable Documentation
addr_6845
unsigned console::cga::addr_6845 static
Definition at line 116 of file console.cc.
Referenced by cursorRefresh(), and init().
buffer
uint16_t* console::cga::buffer static
Definition at line 117 of file console.cc.
Referenced by clear(), init(), and putChar().
pos
uint16_t console::cga::pos static
Definition at line 118 of file console.cc.
Referenced by clear(), cursorRefresh(), init(), and putChar().