Litchi: console::err Namespace Reference
console::err Namespace Reference
Functions
void print (const char *fmt,...)
void printVa (const char *fmt, va_list ap)
Function Documentation
print()
void console::err::print (const char * fmt, ...)
Definition at line 42 of file kernel/printf.cc.
{
             va_list ap;
             va_start(ap, fmt);
             printVa(fmt, ap);
             va_end(ap);
         }
Referenced by std::__throw_bad_function_call(), _kernelPanic(), _kernelWarning(), kdebug::backtrace(), vmem::utils::dumpV(), main(), monitor::main(), and vmem::utils::show().
printVa()
void console::err::printVa (const char * fmt, va_list ap)
Definition at line 37 of file kernel/printf.cc.
{
             ge::printFmtVa(out::putChar, fmt, ap, LIGHT_RED, DEF_BACK);
         }
Referenced by _kernelPanic(), _kernelWarning(), consoleErrPrintC(), and print().