Litchi: mp::lapic Namespace Reference
mp::lapic Namespace Reference
Functions
void init ()
void lapic_eoi ()
void lapic_ipi (int vector)
static void lapicw (int index, int value)
static void microdelay (int us)
void startAP (uint8_t apicid, uint32_t addr)
Variables
volatile uint32_t * lapicKern
physaddr_t lapicPhy
Function Documentation
init()
void mp::lapic::init ()
Definition at line 239 of file mp.cc.
                 {
         using trap::Type;
         // no MP support
         if (!lapicPhy) return;
         // lapicPhy is the physical address of the LAPIC's 4K MMIO
         // region.  Map it in to virtual memory so we can access it.
         lapicKern = static_cast<volatile uint32_t *>(vmem::pgdir::mmioMap(lapicPhy, 4096));
         // Enable local APIC; set spurious interrupt vector.
         lapicw(SVR, ENABLE | (uint32_t) Type::hwSpurious);
         // The timer repeatedly counts down at bus frequency
         // from lapic[TICR] and then issues an interrupt.
         // If we cared more about precise timekeeping,
         // TICR would be calibrated using an external time source.
         lapicw(TDCR, X1);
         lapicw(TIMER, PERIODIC | (uint32_t) Type::hwTimer);
         lapicw(TICR, 10000000);
         // Leave LINT0 of the BSP enabled so that it can get
         // interrupts from the 8259A chip.
         //
         // According to Intel MP Specification, the BIOS should initialize
         // BSP's local APIC in Virtual Wire Mode, in which 8259A's
         // INTR is virtually connected to BSP's LINTIN0. In this mode,
         // we do not need to program the IOAPIC.
         if (mp::thisCPU() != mp::bootstrapCPU)
             lapicw(LINT0, MASKED);
         // Disable NMI (LINT1) on all CPUs
         lapicw(LINT1, MASKED);
         // Disable performance counter overflow interrupts
         // on machines that provide that interrupt entry.
         if (((lapicKern[VER] >> 16) & 0xFF) >= 4)
             lapicw(PCINT, MASKED);
         // Map error interrupt to IRQ_ERROR.
         lapicw(ERROR, (uint32_t) Type::hwError);
         // Clear error status register (requires back-to-back writes).
         lapicw(ESR, 0);
         lapicw(ESR, 0);
         // Ack any outstanding interrupts.
         lapicw(EOI, 0);
         // Send an Init Level De-Assert to synchronize arbitration ID's.
         lapicw(ICRHI, 0);
         lapicw(ICRLO, BCAST | INIT | LEVEL);
         while (lapicKern[ICRLO] & DELIVS);
         // Enable interrupts on the APIC (but not on the processor).
         lapicw(TPR, 0);
     }
Referenced by mp::init().
lapic_eoi()
void mp::lapic::lapic_eoi ()
Definition at line 298 of file mp.cc.
                      {
         if (lapicKern)
             lapicw(EOI, 0);
     }
lapic_ipi()
void mp::lapic::lapic_ipi (int vector)
Definition at line 345 of file mp.cc.
{
         lapicw(ICRLO, OTHERS | FIXED | vector);
         while (lapicKern[ICRLO] & DELIVS);
     }
lapicw()
static void mp::lapic::lapicw (int index, int value) static
Definition at line 234 of file mp.cc.
{
         lapicKern[index] = value;
         lapicKern[ID];  // wait for write to finish, by reading
     }
Referenced by init(), lapic_eoi(), lapic_ipi(), and startAP().
microdelay()
static void mp::lapic::microdelay (int us) static
Definition at line 305 of file mp.cc.
{
     }
Referenced by startAP().
startAP()
void mp::lapic::startAP (uint8_t apicid, uint32_t addr)
Definition at line 310 of file mp.cc.
{
         using namespace x86;
         int i;
         uint16_t *wrv;
         // "The BSP must initialize CMOS shutdown code to 0AH
         // and the warm reset vector (DWORD based at 40:67) to point at
         // the AP startup code prior to the [universal startup algorithm]."
         outb(IO_RTC, 0xF);  // offset 0xF is shutdown code
         outb(IO_RTC + 1, 0x0A);
         wrv = (uint16_t *) KERN_ADDR(0x40 << 4 | 0x67);  // Warm reset vector
         wrv[0] = 0;
         wrv[1] = addr >> 4;
         // "Universal startup algorithm."
         // Send INIT (level-triggered) interrupt to reset other CPU.
         lapicw(ICRHI, apicid << 24);
         lapicw(ICRLO, INIT | LEVEL | ASSERT);
         microdelay(200);
         lapicw(ICRLO, INIT | LEVEL);
         microdelay(100);    // should be 10ms, but too slow in Bochs!
         // Send startup IPI (twice!) to enter code.
         // Regular hardware is supposed to only accept a STARTUP
         // when it is in the halted state due to an INIT.  So the second
         // should be ignored, but it is part of the official Intel algorithm.
         // Bochs complains about the second one.  Too bad for Bochs.
         for (i = 0; i < 2; i++) {
             lapicw(ICRHI, apicid << 24);
             lapicw(ICRLO, STARTUP | (addr >> 12));
             microdelay(200);
         }
     }
Variable Documentation
lapicKern
volatile uint32_t * mp::lapic::lapicKern
Definition at line 231 of file mp.cc.
Referenced by init(), lapic_eoi(), lapic_ipi(), lapicw(), and mp::thisCPU().
lapicPhy
physaddr_t mp::lapic::lapicPhy
Definition at line 230 of file mp.cc.
Referenced by mp::init(), and init().