Litchi: console::serial Namespace Reference
console::serial Namespace Reference
Functions
static void delay (void)
static void init (void)
static void putChar (int c, enum color_t defForeColor, enum color_t defBackColor)
static void sout (int c)
Variables
constexpr bool colored = false
static bool exists
Function Documentation
delay()
static void console::serial::delay (void) static
Definition at line 40 of file console.cc.
{
             x86::inb(0x84);
             x86::inb(0x84);
             x86::inb(0x84);
             x86::inb(0x84);
         }
init()
static void console::serial::init (void) static
Definition at line 49 of file console.cc.
{
             // Turn off the FIFO
             x86::outb(COM1 + COM_FCR, 0);
             // Set speed; requires DLAB latch
             x86::outb(COM1 + COM_LCR, COM_LCR_DLAB);
             x86::outb(COM1 + COM_DLL, (uint8_t) (115200 / 9600));
             x86::outb(COM1 + COM_DLM, 0);
             // 8 data bits, 1 stop bit, parity off; turn off DLAB latch
             x86::outb(COM1 + COM_LCR, COM_LCR_WLEN8 & ~COM_LCR_DLAB);
             // No modem controls
             x86::outb(COM1 + COM_MCR, 0);
             // Enable rcv interrupts
             x86::outb(COM1 + COM_IER, COM_IER_RDI);
             // Clear any preexisting overrun indications and interrupts
             // Serial port doesn't exist if COM_LSR returns 0xFF
             exists = (x86::inb(COM1 + COM_LSR) != 0xFF);
             (void) x86::inb(COM1 + COM_IIR);
             (void) x86::inb(COM1 + COM_RX);
         }
Referenced by console::init().
putChar()
static void console::serial::putChar (int c, enum color_t defForeColor, enum color_t defBackColor) static
Definition at line 82 of file console.cc.
{
             if (exists) {
                 if (colored) {
                     enum color_t foreColor = FORE_COLOR(c) ? FORE_COLOR(c) : defForeColor;
                     enum color_t backColor = BACK_COLOR(c) ? BACK_COLOR(c) : defBackColor;
                     const char *foreCode = ansiForeCode[foreColor];
                     const char *backCode = ansiBackCode[backColor];
                     sout('\x1b');
                     sout('[');
                     while (*foreCode) sout(*(foreCode++));
                     sout(';');
                     while (*backCode) sout(*(backCode++));
                     sout('m');
                 }
                 if ((c & 0xff) == '\b') {
                     sout(c);
                     sout(' ');
                     sout(c);
                 } else {
                     sout(c);
                 }
                 // sout('\x1b');
                 // sout('[');
                 // sout('3');
                 // sout('9');
                 // sout('m');
             }
         }
Referenced by console::out::putChar().
sout()
static void console::serial::sout (int c) inline static
Definition at line 73 of file console.cc.
{
             // int i;
             // for (i = 0;
             //      !(inb(COM1 + COM_LSR) & COM_LSR_TXRDY) && i < 12800;
             //      i++)
             //     delay();
             x86::outb(COM1 + COM_TX, c);
         }
Referenced by putChar().
Variable Documentation
colored
constexpr bool console::serial::colored = false constexpr
Definition at line 37 of file console.cc.
Referenced by putChar().
exists
bool console::serial::exists static
Definition at line 47 of file console.cc.
Referenced by init(), and putChar().