Litchi: task Namespace Reference
task Namespace Reference
Classes
struct Task
Typedefs
using taskid_t = int32_t
Enumerations
enum TaskStatus : int {
TaskStatus::free = 0, TaskStatus::dying, TaskStatus::ready, TaskStatus::running,
TaskStatus::waiting
}
enum TaskType : int { TaskType::user = 0 }
Functions
void allocArray ()
void init ()
void initPerCpu ()
Typedef Documentation
taskid_t
using task::taskid_t = typedef int32_t
Definition at line 9 of file include/task.hh.
Enumeration Type Documentation
TaskStatus
enum task::TaskStatus : int strong
Enumerator
free
dying
ready
running
waiting
Definition at line 11 of file include/task.hh.
                            : int {
         free = 0, dying, ready, running, waiting
     };
TaskType
enum task::TaskType : int strong
Enumerator
user
Definition at line 15 of file include/task.hh.
                          : int {
         user = 0
     };
Function Documentation
allocArray()
void task::allocArray ()
Definition at line 23 of file task.cc.
                       {
         using namespace vmem;
         Task::array = bootAllocCount<Task>(Task::maxCount);
         mem::clear(Task::array, sizeof(Task) * Task::maxCount);
         // expose the task array to user space
         pgdir::staticMap(kernelPageDir,
                          UENVS,
                          ROUNDUP(sizeof(Task) * Task::maxCount, PGSIZE),
                          PHY_ADDR(Task::array),
                          PTE_U);
     }
Referenced by vmem::init().
init()
void task::init ()
Definition at line 36 of file task.cc.
                 {
         print("Initializing tasks...\n");
         // vmem part should have allocated task array
         assert(Task::array != nullptr);
         // construct free list
         for (int i = Task::maxCount - 1; i >= 0; i--) {
             Task::array[i].nextFree = Task::freeList;
             Task::freeList = Task::array + i;
         }
         initPerCpu();
         print("  %<Done\n", WHITE);
     }
Referenced by i386InitLitchi().
initPerCpu()
void task::initPerCpu ()
Definition at line 51 of file task.cc.
                       {
         // now switch gdt from bootstrap gdt to new one, for use of privilege level
         // see kernel/gdt.c
         x86::lgdt(&gdtPD);
         // set segment register (selector) to the correct descriptor
         // the kernel never uses GS or FS, so we leave those set to the user data segment.
         // LS 2 bit: Requested Privilege Level
         asm volatile("movw %%ax,%%gs" : : "a" (GD_UD | 3));
         asm volatile("movw %%ax,%%fs" : : "a" (GD_UD | 3));
         // the kernel does use ES, DS, and SS.
         asm volatile("movw %%ax,%%es" : : "a" (GD_KD));
         asm volatile("movw %%ax,%%ds" : : "a" (GD_KD));
         asm volatile("movw %%ax,%%ss" : : "a" (GD_KD));
         // perform a long jump to set new CS selector
         asm volatile("ljmp %0,$1f\n 1:\n" : : "i" (GD_KT));
     }
Referenced by init().