Litchi: monitor Namespace Reference
monitor Namespace Reference
Classes
struct Command
Typedefs
using FuncType = Result(int argc, char **argv, trap::Frame *tf)
Functions
Result backtrace (int argc, char **argv, trap::Frame *tf)
Result cont (int, char **, trap::Frame *tf)
Result echo (int argc, char **argv, trap::Frame *tf)
Result fuck (int, char **, trap::Frame *)
Result help (int argc, char **argv, trap::Frame *tf)
int main (trap::Frame *tf)
Result page (int, char **, trap::Frame *)
Result parseCmd (char *cmd, trap::Frame *tf)
Result runtask (int argc, char **argv, trap::Frame *tf)
Result si (int, char **, trap::Frame *tf)
Result uname (int argc, char **argv, trap::Frame *tf)
Result vmdumpp (int argc, char **argv, trap::Frame *tf)
Result vmdumpv (int argc, char **argv, trap::Frame *tf)
Result vmshow (int argc, char **argv, trap::Frame *tf)
Variables
struct Command commands []
FuncType help
constexpr int MAX_ARGS = 16
Typedef Documentation
FuncType
using monitor::FuncType = typedef Result(int argc, char **argv, trap::Frame *tf)
Definition at line 24 of file monitor.cc.
Function Documentation
backtrace()
Result monitor::backtrace (int argc, char ** argv, trap::Frame * tf)
Definition at line 59 of file monitor.cc.
{
         kdebug::backtrace();
         return Result::ok;
     }
cont()
Result monitor::cont (int , char ** , trap::Frame * tf)
Definition at line 103 of file monitor.cc.
{
         if (tf) {
             tf->eflags &= ~FL_TF;   // clear Trap Flag (single-step)
             tf->pop();
         } else {
             return Result::noSuchTask;
         }
     }
echo()
Result monitor::echo (int argc, char ** argv, trap::Frame * tf)
Definition at line 42 of file monitor.cc.
{
         for (int i = 1; i < argc; ++i) {
             console::out::print("%<%s ", (i + str::count(argv[i])) % 15 + BLUE, argv[i]);
         }
         console::out::print("\n");
         return Result::ok;
     }
fuck()
Result monitor::fuck (int , char ** , trap::Frame *)
Definition at line 122 of file monitor.cc.
{
         return Result::fuck;
     }
Referenced by describe(), and vmem::pgdir::insert().
help()
Result monitor::help (int argc, char ** argv, trap::Frame * tf)
Definition at line 215 of file monitor.cc.
{
         for (size_t i = 0; i < ARRAY_SIZE(commands); ++i) {
             if (!commands[i].hide)
                 console::out::print("%<%8s%<: %s\n", WHITE, commands[i].cmd, DEF_FORE, commands[i].desc);
         }
         return Result::ok;
     }
main()
int monitor::main (trap::Frame * tf)
The entry of the kernel monitor
Parameters
tf trap frame of current task
Returns
nothing
Definition at line 243 of file monitor.cc.
{
         char *cmd;
         auto lastRet = Result::ok;
         console::out::print("\n");
         while (true) {
             auto color = lastRet != Result::ok ? RED : DEF_FORE;
             // show current task if needed
             if (task::Task::current != nullptr)
                 cmd = console::in::readline("%<Litchi%<[%08x]%<> ",
                                             LIGHT_MAGENTA, WHITE, task::Task::current->id, color);
             else
                 cmd = console::in::readline("%<Litchi%<> ",
                                             LIGHT_MAGENTA, color);
             if (*cmd && cmd[0]) lastRet = parseCmd(cmd, tf);
             if (lastRet != Result::ok) console::err::print("%s: %r\n", cmd, lastRet);
         }
     }
Referenced by trap::handler::debug(), task::Task::destroy(), trap::Frame::dispatch(), and i386InitLitchi().
page()
Result monitor::page (int , char ** , trap::Frame *)
Definition at line 126 of file monitor.cc.
{
         auto count = vmem::PageInfo::freeCount();
         print("%d free pages (%d KB, %d MB)\n", count, count << 2, count << 2 >> 10);
         return Result::ok;
     }
Referenced by task::Task::regionAlloc(), and task::Task::setupMemory().
parseCmd()
Result monitor::parseCmd (char * cmd, trap::Frame * tf)
Definition at line 225 of file monitor.cc.
{
         char *argv[MAX_ARGS + 2];
         int argc = str::splitWs(cmd, argv, MAX_ARGS + 2);
         if (argc == MAX_ARGS + 1) return Result::tooManyArgs;
         else if (argc == -1) return Result::badSyntax;
         for (size_t i = 0; i < ARRAY_SIZE(commands); ++i) {
             if (str::cmpCase(argv[0], commands[i].cmd) == 0) {
                 return commands[i].func(argc, argv, tf);
             }
         }
         return Result::badCommand;
     }
Referenced by main().
runtask()
Result monitor::runtask (int argc, char ** argv, trap::Frame * tf)
Definition at line 92 of file monitor.cc.
{
         using namespace task;
         static bool started = false;
         auto[task, r] = Task::create(embUserElf, TaskType::user,
                                      (char *) EMBUSER_ELF + BINARY_DIR_OFFSET);
         started = true;
         task->run(true);
     }
si()
Result monitor::si (int , char ** , trap::Frame * tf)
Definition at line 113 of file monitor.cc.
{
         if (tf) {
             tf->eflags |= FL_TF;    // set Trap Flag (single-step)
             tf->pop();
         } else {
             return Result::noSuchTask;
         }
     }
uname()
Result monitor::uname (int argc, char ** argv, trap::Frame * tf)
Definition at line 51 of file monitor.cc.
{
         if (argc >= 2 && str::cmp(argv[1], "-a") == 0)
             console::out::print("Litchi v%s by BugenZhao\n", LITCHI_VERSION_TIME);
         else console::out::print("Litchi\n");
         return Result::ok;
     }
vmdumpp()
Result monitor::vmdumpp (int argc, char ** argv, trap::Frame * tf)
Definition at line 83 of file monitor.cc.
{
         if (argc <= 1) return Result::invalidArg;
         physaddr_t beginP = (str::toLong(argv[1], 0));
         physaddr_t endP = (argc >= 3) ? (str::toLong(argv[2], 0)) : beginP;
         vmem::utils::dumpP(vmem::kernelPageDir, beginP, endP);
         return Result::ok;
     }
vmdumpv()
Result monitor::vmdumpv (int argc, char ** argv, trap::Frame * tf)
Definition at line 74 of file monitor.cc.
{
         if (argc <= 1) return Result::invalidArg;
         void *beginV = (void *) (str::toLong(argv[1], 0));
         void *endV = (argc >= 3) ? (void *) (str::toLong(argv[2], 0)) : beginV;
         vmem::utils::dumpV(vmem::kernelPageDir, beginV, endV);
         return Result::ok;
     }
vmshow()
Result monitor::vmshow (int argc, char ** argv, trap::Frame * tf)
Definition at line 65 of file monitor.cc.
{
         if (argc <= 1) return Result::invalidArg;
         void *beginV = (void *) (str::toLong(argv[1], 0));
         void *endV = (argc >= 3) ? (void *) (str::toLong(argv[2], 0)) : beginV;
         vmem::utils::show(vmem::kernelPageDir, beginV, endV);
         return Result::ok;
     }
Variable Documentation
commands
struct Command monitor::commands[]
Definition at line 126 of file monitor.cc.
Referenced by help(), and parseCmd().
help
FuncType monitor::help
Definition at line 39 of file monitor.cc.
MAX_ARGS
constexpr int monitor::MAX_ARGS = 16 constexpr
Definition at line 23 of file monitor.cc.
Referenced by parseCmd().