Litchi: console::in Namespace Reference
console::in Namespace Reference
Functions
char getChar ()
char * readline (const char *promptFmt=nullptr,...)
char * readlineVa (const char *promptFmt, va_list ap)
Variables
static char buf [READLINE_BUF_SIZE]
static char buf [READLINE_BUF_SIZE]
constexpr int READLINE_BUF_SIZE = 4096
Function Documentation
getChar()
char console::in::getChar ()
Definition at line 233 of file console.cc.
                       {
             int c;
             while ((c = kbd::getNextChar()) == 0);
             return c;
         }
Referenced by ksyscall::getChar(), and readlineVa().
readline()
char * console::in::readline (const char * promptFmt = nullptr, ...)
Definition at line 14 of file kernel/readline.cc.
{
         char *ret;
         va_list ap;
         va_start(ap, promptFmt);
         ret = readlineVa(promptFmt, ap);
         va_end(ap);
         return ret;
     }
Referenced by main(), and monitor::main().
readlineVa()
char * console::in::readlineVa (const char * promptFmt, va_list ap)
Definition at line 23 of file kernel/readline.cc.
{
         int c;
         int idx = 0;
         if (promptFmt) out::printVa(promptFmt, ap);
         while (true) {
             c = getChar();
             if (c < 0) {
                 kernelPanic("Illegal input: 0x%x", c);
             } else if (isSimpleChar(c) && idx < READLINE_BUF_SIZE - 1) {
                 out::putChar(c);
                 buf[idx++] = c;
             } else if (c == '\b' && idx > 0) {
                 out::putChar(c);
                 idx--;
             } else if (c == '\r' || c == '\n') {
                 out::putChar('\n');
                 buf[idx] = '\0';
                 break;
             }
         }
         return buf;
     }
Referenced by readline().
Variable Documentation
buf [1/2]
char console::in::buf[READLINE_BUF_SIZE] static
Definition at line 11 of file kernel/readline.cc.
Referenced by vmem::utils::flagStr(), and readlineVa().
buf [2/2]
char console::in::buf[READLINE_BUF_SIZE] static
Definition at line 16 of file user/lib/readline.cc.
READLINE_BUF_SIZE
constexpr int console::in::READLINE_BUF_SIZE = 4096 constexpr
Definition at line 13 of file stdin.hh.
Referenced by readlineVa().