Litchi: str Namespace Reference
str Namespace Reference
Functions
char * append (char *dest, const char *src)
int cmp (const char *lhs, const char *rhs)
int cmpCase (const char *lhs, const char *rhs)
char * copy (char *dest, const char *src, size_t count=SIZE_MAX)
size_t count (const char *str)
char * find (const char *str, char c)
int split (char *str, const char *delimiters, char **resultBuf, size_t bufCount, bool ignoreQuo)
int splitWs (char *str, char **resultBuf, size_t bufCount)
long toLong (const char *ptr, int base)
Function Documentation
append()
char * str::append (char * dest, const char * src)
Definition at line 112 of file string.cc.
{
         size_t len = count(dest);
         copy(dest + len, src);
         return dest;
     }
cmp()
int str::cmp (const char * lhs, const char * rhs)
Definition at line 126 of file string.cc.
{
         while (*lhs && *rhs && *lhs == *rhs)
             lhs++, rhs++;
         return *lhs - *rhs;
     }
Referenced by monitor::Command::operator<(), and monitor::uname().
cmpCase()
int str::cmpCase (const char * lhs, const char * rhs)
Definition at line 132 of file string.cc.
{
         char a, b;
         while (*lhs && *rhs) {
             a = isCapital(*lhs) ? ((*lhs) - 'A' + 'a') : *lhs;
             b = isCapital(*rhs) ? ((*rhs) - 'A' + 'a') : *rhs;
             if (a != b) return a - b;
             lhs++, rhs++;
         }
         return *lhs - *rhs;
     }
Referenced by monitor::parseCmd().
copy()
char * str::copy (char * dest, const char * src, size_t count = SIZE_MAX)
Definition at line 118 of file string.cc.
{
         char *ret = dest;
         while (*src && count--)
             *(dest++) = *(src++);
         *dest = 0;
         return ret;
     }
Referenced by append(), and task::Task::create().
count()
size_t str::count (const char * str)
Definition at line 105 of file string.cc.
{
         size_t len = 0;
         while (*(str++))
             len++;
         return len;
     }
Referenced by __builtin_memmove(), append(), vmem::bootAllocCount(), mem::clear(), mem::cmp(), copy(), mem::copy(), monitor::echo(), vmem::PageInfo::freeCount(), mem::move(), monitor::page(), console::ge::printFmtVa(), ksyscall::putString(), readseg(), mem::set(), and split().
find()
char * str::find (const char * str, char c)
Definition at line 144 of file string.cc.
{
         for (; *str; str++)
             if (*str == c) return (char *) str;
         return nullptr;
     }
Referenced by split().
split()
int str::split (char * str, const char * delimiters, char ** resultBuf, size_t bufCount, bool ignoreQuo)
Definition at line 153 of file string.cc.
{
         if (str == NULL) return -1;
         size_t count = 0;
         int quo = 0;
         while (count < bufCount - 1) {
             while (*str && find(delimiters, *str) != NULL) *str++ = '\0';
             if (*str == '\0') break;
             resultBuf[count++] = str;
             while (*str && (quo || find(delimiters, *str) == NULL)) {
                 if (!ignoreQuo && *str == '\"') {
                     if (!quo) resultBuf[count - 1] = str + 1;
                     quo = !quo;
                     *str = '\0';
                 }
                 str++;
             }
         }
         if (quo) return -1;
         resultBuf[count] = NULL;
         return count;
     }
Referenced by splitWs().
splitWs()
int str::splitWs (char * str, char ** resultBuf, size_t bufCount)
Definition at line 181 of file string.cc.
{
         return split(str, WHITESPACE, resultBuf, bufCount, true);
     }
Referenced by monitor::parseCmd().
toLong()
long str::toLong (const char * ptr, int base)
Definition at line 11 of file strtol.cc.
{
         const char *str = ptr;
         int c;
         bool neg = false;
         do {
             c = *str++;
         } while (isWhiteSpace(c));
         if (c == '-') {
             neg = true;
             c = *str++;
         } else if (c == '+') {
             neg = false;
             c = *str++;
         }
         if ((base == 0 || base == 16) && c == '0' && (*str == 'x' || *str == 'X')) {
             // hex
             c = str[1];
             str += 2;
             base = 16;
         } else if (base == 0) {
             // oct or dec
             if (c == '0') base = 8;
             else base = 10;
         }
         long long acc = 0;
         for (;; c = *str++) {
             if (isDigit(c)) c -= '0';
             else if (isCapital(c)) c -= 'A' - 10;
             else if (isLittle(c)) c -= 'a' - 10;
             else break;
             if (c >= base) break;
             acc = acc * base + c;
         }
         if (neg) acc = -acc;
         return (long) acc;
     }
Referenced by monitor::vmdumpp(), monitor::vmdumpv(), and monitor::vmshow().