Litchi: mp Namespace Reference
mp Namespace Reference
Namespaces
lapic
Classes
struct ConfTable
struct CPUInfo
struct FPStruct
struct IOAPIC
struct ProcessorAPIC
Enumerations
enum APICType : uint8_t {
MPPROC, MPBUS, MPIOAPIC, MPIOINTR,
MPLINTR
}
Functions
struct mp::FPStruct __attribute__ ((__packed__))
template<typename T >
static bool checksumOk (const T *addr, size_t len=sizeof(T))
void init ()
static FPStruct * searchFP ()
CPUInfo * thisCPU ()
Variables
enum mp::APICType __attribute__
CPUInfo * bootstrapCPU = nullptr
int cpuCount = 0
CPUInfo cpus [MAX_CPU_COUNT] = {}
bool isMP = false
constexpr auto MAX_CPU_COUNT = 32
Enumeration Type Documentation
APICType
enum mp::APICType : uint8_t
Enumerator
MPPROC
MPBUS
MPIOAPIC
MPIOINTR
MPLINTR
Definition at line 49 of file mp.cc.
                   : uint8_t {
         MPPROC,     // One per processor
         MPBUS,      // One per bus
         MPIOAPIC,   // One per I/O APIC
         MPIOINTR,   // One per bus interrupt source
         MPLINTR     // One per system interrupt source
     };
Function Documentation
__attribute__()
struct mp::FPStruct mp::__attribute__ ((__packed__))
checksumOk()
template<typename T > static bool mp::checksumOk (const T * addr, size_t len = sizeof(T)) static
Definition at line 79 of file mp.cc.
{
         uint8_t sum = 0;
         for (size_t i = 0; i < len; ++i) {
             sum += ((uint8_t *) addr)[i];
         }
         return sum == 0;
     }
Referenced by init(), and searchFP().
init()
void mp::init ()
Definition at line 129 of file mp.cc.
                 {
         console::out::print("Initializing multi-processor...\n");
         auto fp = searchFP();
         if (fp == nullptr) {
             console::out::print("No multi-processor support.\n");
             cpuCount = 1;
             cpus[0].id = 0;
             cpus[0].status = CPUInfo::Status::started;
             bootstrapCPU = &cpus[0];
             return;
         }
         // get Configuration Table
         auto conf = (ConfTable *) KERN_ADDR(fp->configuration_table);
         assert(conf != nullptr);                            // no default configuration support
         assert(mem::cmp(conf->signature, "PCMP", 4) == 0);  // signature
         assert(checksumOk(conf, conf->length));             // base checksum
         assert(checksumOk((uint8_t *) conf + conf->length, conf->extended_table_length));   // extended checksum
         // APIC OEM ID
         char oem[9] = {};
         mem::copy(oem, conf->oem_id, sizeof(conf->oem_id));
         console::out::print("  MP Conf Table OEM: %s\n", oem);
         // save local APIC MMIO physical address
         lapic::lapicPhy = conf->lapic_address;
         // **After** the table, there are entry_count entries describing more information about the system
         uintptr_t entries = (uintptr_t) conf + sizeof(ConfTable);
         ProcessorAPIC *proc;
         bool isBootstrap;
         console::out::print("  Found CPU");
         for (int i = 0; i < conf->entry_count; ++i) {
             switch (*(APICType *) entries) {
                 case MPPROC:    // processor entry type
                     proc = (ProcessorAPIC *) entries;
                     isBootstrap = proc->flags & 0x02;
                     if (cpuCount < MAX_CPU_COUNT) { // add this CPU
                         cpus[cpuCount].id = cpuCount;
                         console::out::print(" %d%s", proc->local_apic_id, isBootstrap ? "[B]" : "");
                         if (isBootstrap) bootstrapCPU = &cpus[cpuCount];
                         cpuCount++;
                     }
                     entries += sizeof(ProcessorAPIC);
                     break;
                 default:        // other apic entry
                     entries += 8;
                     break;
             }
         }
         bootstrapCPU->status = CPUInfo::Status::started;
         isMP = cpuCount > 1;
         lapic::init();
         console::out::print("\n  %<Done\n", WHITE);
     }
Referenced by i386InitLitchi().
searchFP()
static FPStruct* mp::searchFP () static
Definition at line 88 of file mp.cc.
{
         // Search FPStruct in [addr, addr+len)
         auto search = [](physaddr_t addr, size_t len) -> FPStruct * {
             auto end = addr + len;
             for (; addr < end; addr += sizeof(FPStruct)) {
                 auto fp = static_cast<FPStruct *>(KERN_ADDR(addr));
                 // check signature and checksum
                 if (mem::cmp(fp->signature, "_MP_", 4) == 0 && checksumOk(fp)) {
                     console::out::print("  Found FPStruct at %p\n", fp);
                     return fp;
                 }
             }
             return nullptr;
         };
         // there are 3 possible positions
         // 1. Check the first KB of the Extended BIOS Data Area (EBDA)
         constexpr uint16_t bdaSeg = 0x40;
         auto bda = (uint8_t *) KERN_ADDR(bdaSeg << 4);
         if (auto ebdaSeg = *(uint16_t *) (bda + 0x0e); ebdaSeg) {   // EBDA exists
             auto ebdaPhy = ebdaSeg << 4;
             if (auto fp = search(ebdaPhy, 1024); fp) return fp;
         }
         // 2. No EBDA, check the last KB of system base memory
         auto phy = *(uint16_t *) (bda + 0x13) * 1024;
         if (auto fp = search(phy - 1024, 1024); fp) return fp;
         // 3. Check the BIOS read-only memory space between 0xe0000 and 0xfffff
         return search(0xe0000, 0xfffff - 0xe0000);
     }
Referenced by init().
thisCPU()
CPUInfo * mp::thisCPU ()
Definition at line 352 of file mp.cc.
{
         using namespace lapic;
         int num = lapicKern == nullptr ? 0 : lapicKern[ID] >> 24;
         return &cpus[num];
     }
Referenced by mp::lapic::init().
Variable Documentation
__attribute__
struct mp::IOAPIC mp::__attribute__
bootstrapCPU
CPUInfo * mp::bootstrapCPU = nullptr
Definition at line 124 of file mp.cc.
Referenced by init(), and mp::lapic::init().
cpuCount
int mp::cpuCount = 0
Definition at line 122 of file mp.cc.
Referenced by init().
cpus
CPUInfo mp::cpus = {}
Definition at line 123 of file mp.cc.
Referenced by init(), and thisCPU().
isMP
bool mp::isMP = false
Definition at line 125 of file mp.cc.
Referenced by init().
MAX_CPU_COUNT
constexpr auto mp::MAX_CPU_COUNT = 32 constexpr
Definition at line 25 of file mp.hh.
Referenced by init().