Litchi: trap::handler Namespace Reference
trap::handler Namespace Reference
Functions
void debug (Frame *tf)
void pageFault (Frame *tf)
uint32_t syscall (Frame *tf)
Function Documentation
debug()
void trap::handler::debug (Frame * tf)
Definition at line 180 of file trap.cc.
{
         print("eip = %p\n", tf->eip);
         monitor::main(tf);
     }
Referenced by trap::describe(), trap::Frame::dispatch(), and trap::init().
pageFault()
void trap::handler::pageFault (Frame * tf)
Definition at line 159 of file trap.cc.
{
         // get fault virtual address
         auto faultVa = x86::rcr2();
         if ((tf->cs & 0b11) == 0) {
             kernelPanic("Unhandled page fault (%p) from kernel\n", faultVa);
         } else {
             print("[%08x] Unhandled page fault (at %p) [%s, %s, %s]\n",
                   task::Task::current->id, faultVa,
                   tf->err & 4 ? "user" : "kernel",
                   tf->err & 2 ? "write" : "read",
                   tf->err & 1 ? "protection" : "not-present");
             task::Task::current->destroy(true); // will trap into monitor
         }
     }
Referenced by trap::describe(), and trap::Frame::dispatch().
syscall()
uint32_t trap::handler::syscall (Frame * tf)
Definition at line 175 of file trap.cc.
{
         return ksyscall::main(static_cast<ksyscall::Num>(tf->regs.eax),
                               tf->regs.edx, tf->regs.ecx, tf->regs.ebx, tf->regs.edi, tf->regs.esi);
     }
Referenced by syscall().