Litchi: ksyscall Namespace Reference
ksyscall Namespace Reference
Enumerations
enum Num : uint32_t { Num::putChar, Num::putString, Num::getChar, Num::exit }
Functions
void exit ()
char getChar ()
int32_t main (Num type, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5)
void putChar (int c)
void putString (const uint16_t *str, size_t count)
Enumeration Type Documentation
Num
enum ksyscall::Num : uint32_t strong
Enumerator
putChar
putString
getChar
exit
Definition at line 11 of file syscall.hh.
                     : uint32_t {
         putChar,
         putString,
         getChar,
         exit
     };
Function Documentation
exit()
void ksyscall::exit ()
Definition at line 49 of file ksyscall.cc.
                 {
         task::Task::current->destroy(false);
     }
Referenced by main().
getChar()
char ksyscall::getChar ()
Definition at line 53 of file ksyscall.cc.
                    {
         return console::in::getChar();
     }
Referenced by main().
main()
int32_t ksyscall::main (Num type, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5)
Definition at line 13 of file ksyscall.cc.
{
         switch (type) {
             case Num::putChar:
                 putChar(a1);
                 return 0;
             case Num::putString:
                 putString((const uint16_t *) a1, a2);
                 return 0;
             case Num::exit:
                 exit();
                 return 0;
             case Num::getChar:
                 return getChar();
         }
         return 0;
     }
Referenced by trap::handler::syscall().
putChar()
void ksyscall::putChar (int c)
Definition at line 32 of file ksyscall.cc.
{
         if (c & 0x00ff) {
             console::out::putChar(c);
         }
     }
Referenced by main().
putString()
void ksyscall::putString (const uint16_t * str, size_t count)
Definition at line 38 of file ksyscall.cc.
{
         // check if user is cheating us with our privilege
         if (!vmem::pgdir::userCheck(task::Task::current->pageDir, str, count, PTE_U)) {
             console::out::print("[%08x] Invalid memory access in [%p, %p)\n",
                                 task::Task::current->id, str, str + count);
             task::Task::current->destroy(true);
         }
         // put all chars
         for (size_t i = 0; i < count; ++i) console::out::putChar(str[i]);
     }
Referenced by console::PrintBuf::flush(), main(), and pageFault4().