Litchi: vmem::pgdir Namespace Reference
vmem::pgdir Namespace Reference
Functions
void alloc ()
std::tuple< PageInfo *, pte_t * > findInfo (pde_t *pageDir, const void *va)
pte_t * findPte (pde_t *pageDir, const void *va, bool create)
static void init ()
static void init ()
Result insert (pde_t *pageDir, struct PageInfo *pp, void *va, int perm)
void invalidateTLB (pde_t *pageDir, void *va)
void * mmioMap (physaddr_t pa, size_t size)
void remove (pde_t *pageDir, void *va)
void staticMap (pde_t *pageDir, uintptr_t va, size_t size, physaddr_t pa, int perm)
bool userCheck (pde_t *pageDir, const void *va, size_t size, int perm)
Function Documentation
alloc()
void vmem::pgdir::alloc ()
Definition at line 183 of file vmem.cc.
                  {
         // Create kernel page dir
         kernelPageDir = (pde_t *) bootAlloc(PGSIZE);
         mem::clear(kernelPageDir, PGSIZE);
         // Map itself to va: UVPT (user virtual page table)
         kernelPageDir[PDX(UVPT)] = PHY_ADDR(kernelPageDir) | PTE_U | PTE_P;
         //    printFmt("%p %p\n", UVPT, PHY_ADDR(kernelPageDir));
     }
Referenced by task::Task::create(), and vmem::init().
findInfo()
std::tuple< PageInfo *, pte_t * > vmem::pgdir::findInfo (pde_t * pageDir, const void * va)
Definition at line 228 of file vmem.cc.
{
         pte_t *pte = findPte(pageDir, va, 0);
         // No page or page not present
         if (pte == nullptr || !((*pte) & PTE_P)) return {nullptr, nullptr};
         // Get pa from pte, then get page info from pa
         return {PageInfo::fromPhy(PTE_ADDR(*pte)), pte };
     }
Referenced by remove().
findPte()
pte_t * vmem::pgdir::findPte (pde_t * pageDir, const void * va, bool create)
Definition at line 196 of file vmem.cc.
{
         uint32_t pdx = PDX(va);     // Page directory index
         uint32_t ptx = PTX(va);     // Page table index
         pde_t *pde = pageDir + pdx; // Page directory entry
         if ((*pde) & PTE_P) {
             // Entry present
             // Clear the least significant 10 bits (flags) to get the pt address,
             //  then convert it to virtual address in order to access
             pte_t *pageTable = (pte_t *) KERN_ADDR(PTE_ADDR(*pde));
             return pageTable + ptx;
         } else if (!create) {
             return nullptr;
         } else {
             // Allocate a new **PAGE TABLE** page's info
             struct PageInfo *pp = PageInfo::alloc(true);
             if (pp == nullptr) { return nullptr; }    // Allocation fails
             pp->refCount++;
             mem::clear(pp->toKernV(), PGSIZE); // Clear the real page
             // Actually insert the page table page into pageDir+idx (*pde)
             *pde = pp->toPhy() | PTE_P | PTE_U | PTE_W; // Set permissive flags
             invalidateTLB(pageDir, (void *) va);
             pte_t *pageTable = (pte_t *) KERN_ADDR(PTE_ADDR(*pde));
             return pageTable + ptx;
         }
     }
Referenced by vmem::utils::dumpV(), findInfo(), insert(), vmem::utils::show(), staticMap(), and userCheck().
init() [1/2]
static void vmem::pgdir::init (void) static
Definition at line 298 of file vmem.cc.
{
         // Map PageInfo::array at va UPAGES for user (read-only)
         staticMap(kernelPageDir, UPAGES, PTSIZE, PHY_ADDR(PageInfo::array), PTE_U);
         // Map kernel stack at va KSTACKTOP-KSTKSIZE
         staticMap(kernelPageDir, KSTACKTOP - KSTKSIZE, KSTKSIZE, PHY_ADDR(bootstack), PTE_W);
         // Map all of physical memory in [0, 2^32 - KERNBASE) at va KERNBASE
         staticMap(kernelPageDir, KERNBASE, ~KERNBASE, 0, PTE_W);
         // Actually load page dir
         x86::lcr3(PHY_ADDR(kernelPageDir));
         // Set other cr0 flags
         uint32_t cr0 = x86::rcr0();
         cr0 |= CR0_PE | CR0_PG | CR0_AM | CR0_WP | CR0_NE | CR0_MP;
         cr0 &= ~(CR0_TS | CR0_EM);
         x86::lcr0(cr0);
         // Do some checks
         assert(*(uint64_t *) UPAGES == *(uint64_t *) PageInfo::array);
         assert(*(uint32_t *) (KSTACKTOP - (bootstacktop - (char *) &cr0)) == cr0);
         struct PageInfo *pp0, *pp1;
         void *va2gb = (void *) 0x80000000;
         assert(pp0 = PageInfo::alloc(false));
         mem::set(pp0->toKernV(), 0x18, PGSIZE);
         insert(kernelPageDir, pp0, va2gb, PTE_W);
         assert(pp0->refCount == 1);
         assert(*(int64_t *) va2gb == 0x1818181818181818);
         assert(pp1 = PageInfo::alloc(false));
         mem::set(pp1->toKernV(), 0x10, PGSIZE);
         insert(kernelPageDir, pp1, va2gb, PTE_W);
         assert(pp0->refCount == 0);
         assert(pp0->nextFree != nullptr);
         assert(*(int64_t *) va2gb == 0x1010101010101010);
         remove(kernelPageDir, va2gb);
         assert(pp1->refCount == 0);
         assert(pp1->nextFree != nullptr);
     }
Referenced by vmem::init().
init() [2/2]
static void vmem::pgdir::init () static
insert()
Result vmem::pgdir::insert (pde_t * pageDir, struct PageInfo * pp, void * va, int perm)
Definition at line 250 of file vmem.cc.
{
         pte_t *pte = findPte(pageDir, va, 1);
         if (pte == nullptr) return Result::fuck;
         // First, inc refCount of pp
         pp->refCount++;
         if ((*pte) & PTE_P) {
             // Entry already present
             // Corner-case won't cause bug since we've already inc the ref count,
             //  then it (pp) won't be freed.
             remove(pageDir, va);
         }
         *pte = pp->toPhy() | perm | PTE_P;
         // Invalidate TLB since we may have updated an entry
         invalidateTLB(pageDir, va);
         return Result::ok;
     }
Referenced by init(), and task::Task::regionAlloc().
invalidateTLB()
void vmem::pgdir::invalidateTLB (pde_t * pageDir, void * va)
Definition at line 343 of file vmem.cc.
{
         // Flush the entry only if we're modifying the current address space.
         // For now, there is only one address space, so always invalidate.
         x86::invlpg(va);
     }
Referenced by findPte(), insert(), remove(), and staticMap().
mmioMap()
void * vmem::pgdir::mmioMap (physaddr_t pa, size_t size)
Definition at line 284 of file vmem.cc.
{
         static uintptr_t next = MMIOBASE;
         size = ROUNDUP(size, PGSIZE);
         if (next + size >= MMIOLIM || next + size < MMIOBASE)
             kernelPanic("Cannot map vm for mmio (pa %p, size %u)", pa, size);
         // cache-disable, write-through
         staticMap(kernelPageDir, next, size, pa, PTE_W | PTE_PCD | PTE_PWT);
         next += size;
         return (void *) (next - size);
     }
Referenced by mp::lapic::init().
remove()
void vmem::pgdir::remove (pde_t * pageDir, void * va)
Definition at line 237 of file vmem.cc.
{
         auto [pp, pte] = findInfo(pageDir, va);
         if (pp && (*pte) & PTE_P) {
             // Dec the ref, and mark the physical page free if necessary
             pp->decRef();
             // Clear page table entry
             *pte = 0;
             // Invalidate TLB since we removed an entry
             invalidateTLB(pageDir, va);
         }
     }
Referenced by task::Task::free(), init(), and insert().
staticMap()
void vmem::pgdir::staticMap (pde_t * pageDir, uintptr_t va, size_t size, physaddr_t pa, int perm)
Definition at line 270 of file vmem.cc.
{
         uint32_t offset = 0;
         // There might be multiple pte's to find and set
         while (offset < size) {
             // Get the page table entry
             pte_t *pte = findPte(pageDir, (const void *) (va + offset), 1);
             // Actually set the pte to map the page
             *pte = (pa + offset) | PTE_P | perm;
             invalidateTLB(pageDir, (void *) (va + offset));
             offset += PGSIZE;
         }
     }
Referenced by task::allocArray(), init(), and mmioMap().
userCheck()
bool vmem::pgdir::userCheck (pde_t * pageDir, const void * va, size_t size, int perm)
Definition at line 352 of file vmem.cc.
{
         perm = perm | PTE_P;
         auto va_it = (uint32_t) va;
         for (; va_it < (uint32_t) va + size; va_it += PGSIZE) {
             // out of user limit
             if ((uintptr_t) va_it >= ULIM) goto bad;
             // perm not satisfied
             pte_t *pte = findPte(pageDir, (const void *) va_it, false);
             if (pte == NULL) goto bad;
             if (!(*pte & perm)) goto bad;
         }
         return true;
         bad:
         return false;
     }
Referenced by ksyscall::putString().