Litchi: lrandom Namespace Reference
lrandom Namespace Reference
Functions
uint16_t rand ()
Variables
static int next = (int) TIMESEED
Function Documentation
rand()
uint16_t lrandom::rand ()
Definition at line 11 of file random.cc.
                     {
         next = next * 1103515245 + 12345;
         return static_cast<uint16_t>(next / 65536);
     }
Referenced by task::Task::alloc().
Variable Documentation
next
int lrandom::next = (int) TIMESEED static
Definition at line 9 of file random.cc.
Referenced by vmem::bootAlloc(), vmem::pgdir::mmioMap(), and rand().