Litchi: pckbd.c File Reference
pckbd.c File Reference
#include <kernel/pckbd.h>
#include <include/x86.h>
#include <include/cstdout.h>
#include <include/color.h>
#include <include/types.h>
Macros
#define ALT (1<<2)
#define C(x) (x - '@')
#define CAPSLOCK (1<<3)
#define CMDBYTE (KC8_TRANS|KC8_CPU|KC8_MENABLE|KC8_KENABLE)
#define CTL (1<<1)
#define E0ESC (1<<6)
#define K_LDCMDBYTE 0x60
#define K_RDCMDBYTE 0x20
#define KBC_AUXDISABLE 0xa7 /* disable auxiliary port */
#define KBC_AUXECHO 0xd3 /* echo to auxiliary port */
#define KBC_AUXENABLE 0xa8 /* enable auxiliary port */
#define KBC_AUXTEST 0xa9 /* test auxiliary port */
#define KBC_AUXWRITE 0xd4 /* write to auxiliary port */
#define KBC_DISABLE 0xF5 /* as per KBC_SETDEFAULT, but also disable key scanning */
#define KBC_ECHO 0xEE /* request an echo from the keyboard */
#define KBC_ENABLE 0xF4 /* enable key scanning */
#define KBC_KBDDISABLE 0xad /* disable keyboard port */
#define KBC_KBDECHO 0xd2 /* echo to keyboard port */
#define KBC_KBDENABLE 0xae /* enable keyboard port */
#define KBC_KBDTEST 0xab /* test keyboard port */
#define KBC_MODEIND 0xED /* set mode indicators(i.e. LEDs) */
#define KBC_PULSE0 0xfe /* pulse output bit 0 */
#define KBC_PULSE1 0xfd /* pulse output bit 1 */
#define KBC_PULSE2 0xfb /* pulse output bit 2 */
#define KBC_PULSE3 0xf7 /* pulse output bit 3 */
#define KBC_RAMREAD 0x20 /* read from RAM */
#define KBC_RAMWRITE 0x60 /* write to RAM */
#define KBC_RESEND 0xFE /* request the keyboard resend the last byte */
#define KBC_RESET 0xFF /* reset the keyboard */
#define KBC_SELFTEST 0xaa /* start self-test */
#define KBC_SETDEFAULT 0xF6 /* resets keyboard to its power-on defaults */
#define KBC_SETTABLE 0xF0 /* set scancode translation table */
#define KBC_TYPEMATIC 0xF3 /* set typematic rate and delay */
#define KBCMDP 0x64 /* kbd controller port(O) */
#define KBD_BUF_SIZE 512
#define KBDATAP 0x60 /* kbd data port(I) */
#define KBOUTP 0x60 /* kbd data port(O) */
#define KBR_ACK 0xFA /* received a valid command */
#define KBR_BREAK 0xF0 /* break code prefix - sent on key release */
#define KBR_ECHO 0xEE /* echo response */
#define KBR_EXTENDED 0xE0 /* extended key sequence */
#define KBR_FAILURE 0xFD /* diagnosic failure */
#define KBR_OVERRUN 0x00 /* flooded */
#define KBR_RESEND 0xFE /* needs resend of command */
#define KBR_RSTDONE 0xAA /* reset complete */
#define KBS_DIB 0x01 /* kbd data in buffer */
#define KBS_IBF 0x02 /* kbd input buffer low */
#define KBS_NOSEC 0x10 /* kbd security lock not engaged */
#define KBS_OCMD 0x08 /* kbd output buffer has command */
#define KBS_PERR 0x80 /* kbd parity error */
#define KBS_RERR 0x40 /* kbd receive error */
#define KBS_TERR 0x20 /* kbd transmission error or from mouse */
#define KBS_WARM 0x04 /* kbd input buffer low */
#define KBSTATP 0x64 /* kbd controller status port(I) */
#define KC8_CPU 0x04 /* exit from protected mode reset */
#define KC8_IGNSEC 0x08 /* ignore security lock */
#define KC8_KDISABLE 0x10 /* disable keyboard */
#define KC8_KENABLE 0x01 /* enable keyboard interrupt */
#define KC8_MDISABLE 0x20 /* disable mouse */
#define KC8_MENABLE 0x02 /* enable mouse interrupt */
#define KC8_TRANS 0x40 /* convert to old scan codes */
#define KEY_DEL 0xE9
#define KEY_DN 0xE3
#define KEY_END 0xE1
#define KEY_HOME 0xE0
#define KEY_INS 0xE8
#define KEY_LF 0xE4
#define KEY_PGDN 0xE7
#define KEY_PGUP 0xE6
#define KEY_RT 0xE5
#define KEY_UP 0xE2
#define NO 0
#define NUMLOCK (1<<4)
#define SCROLLLOCK (1<<5)
#define SHIFT (1<<0)
Functions
static int _kbdProcessData (void)
int kbdGetNextChar (void)
void kbdInit (void)
static void kbdIntr (void)
Variables
uint8_t * charcode [4]
uint8_t ctlmap [256]
struct {
uint8_t buffer [KBD_BUF_SIZE]
uint32_t readPos
uint32_t writePos
} kbdBuffer
uint8_t normalmap [256]
uint8_t shiftcode [256]
uint8_t shiftmap [256]
uint8_t togglecode [256]
Macro Definition Documentation
ALT
#define ALT (1<<2)
Definition at line 98 of file pckbd.c.
C
#define C (x) (x - '@')
Definition at line 165 of file pckbd.c.
CAPSLOCK
#define CAPSLOCK (1<<3)
Definition at line 100 of file pckbd.c.
CMDBYTE
#define CMDBYTE (KC8_TRANS|KC8_CPU|KC8_MENABLE|KC8_KENABLE)
Definition at line 66 of file pckbd.c.
CTL
#define CTL (1<<1)
Definition at line 97 of file pckbd.c.
E0ESC
#define E0ESC (1<<6)
Definition at line 104 of file pckbd.c.
K_LDCMDBYTE
#define K_LDCMDBYTE 0x60
Definition at line 57 of file pckbd.c.
K_RDCMDBYTE
#define K_RDCMDBYTE 0x20
Definition at line 56 of file pckbd.c.
KBC_AUXDISABLE
#define KBC_AUXDISABLE 0xa7 /* disable auxiliary port */
Definition at line 38 of file pckbd.c.
KBC_AUXECHO
#define KBC_AUXECHO 0xd3 /* echo to auxiliary port */
Definition at line 42 of file pckbd.c.
KBC_AUXENABLE
#define KBC_AUXENABLE 0xa8 /* enable auxiliary port */
Definition at line 39 of file pckbd.c.
KBC_AUXTEST
#define KBC_AUXTEST 0xa9 /* test auxiliary port */
Definition at line 40 of file pckbd.c.
KBC_AUXWRITE
#define KBC_AUXWRITE 0xd4 /* write to auxiliary port */
Definition at line 43 of file pckbd.c.
KBC_DISABLE
#define KBC_DISABLE 0xF5 /* as per KBC_SETDEFAULT, but also disable key scanning */
Definition at line 72 of file pckbd.c.
KBC_ECHO
#define KBC_ECHO 0xEE /* request an echo from the keyboard */
Definition at line 77 of file pckbd.c.
KBC_ENABLE
#define KBC_ENABLE 0xF4 /* enable key scanning */
Definition at line 73 of file pckbd.c.
KBC_KBDDISABLE
#define KBC_KBDDISABLE 0xad /* disable keyboard port */
Definition at line 46 of file pckbd.c.
KBC_KBDECHO
#define KBC_KBDECHO 0xd2 /* echo to keyboard port */
Definition at line 41 of file pckbd.c.
KBC_KBDENABLE
#define KBC_KBDENABLE 0xae /* enable keyboard port */
Definition at line 47 of file pckbd.c.
KBC_KBDTEST
#define KBC_KBDTEST 0xab /* test keyboard port */
Definition at line 45 of file pckbd.c.
KBC_MODEIND
#define KBC_MODEIND 0xED /* set mode indicators(i.e. LEDs) */
Definition at line 76 of file pckbd.c.
KBC_PULSE0
#define KBC_PULSE0 0xfe /* pulse output bit 0 */
Definition at line 48 of file pckbd.c.
KBC_PULSE1
#define KBC_PULSE1 0xfd /* pulse output bit 1 */
Definition at line 49 of file pckbd.c.
KBC_PULSE2
#define KBC_PULSE2 0xfb /* pulse output bit 2 */
Definition at line 50 of file pckbd.c.
KBC_PULSE3
#define KBC_PULSE3 0xf7 /* pulse output bit 3 */
Definition at line 51 of file pckbd.c.
KBC_RAMREAD
#define KBC_RAMREAD 0x20 /* read from RAM */
Definition at line 36 of file pckbd.c.
KBC_RAMWRITE
#define KBC_RAMWRITE 0x60 /* write to RAM */
Definition at line 37 of file pckbd.c.
KBC_RESEND
#define KBC_RESEND 0xFE /* request the keyboard resend the last byte */
Definition at line 70 of file pckbd.c.
KBC_RESET
#define KBC_RESET 0xFF /* reset the keyboard */
Definition at line 69 of file pckbd.c.
KBC_SELFTEST
#define KBC_SELFTEST 0xaa /* start self-test */
Definition at line 44 of file pckbd.c.
KBC_SETDEFAULT
#define KBC_SETDEFAULT 0xF6 /* resets keyboard to its power-on defaults */
Definition at line 71 of file pckbd.c.
KBC_SETTABLE
#define KBC_SETTABLE 0xF0 /* set scancode translation table */
Definition at line 75 of file pckbd.c.
KBC_TYPEMATIC
#define KBC_TYPEMATIC 0xF3 /* set typematic rate and delay */
Definition at line 74 of file pckbd.c.
KBCMDP
#define KBCMDP 0x64 /* kbd controller port(O) */
Definition at line 35 of file pckbd.c.
KBD_BUF_SIZE
#define KBD_BUF_SIZE 512
Definition at line 191 of file pckbd.c.
KBDATAP
#define KBDATAP 0x60 /* kbd data port(I) */
Definition at line 53 of file pckbd.c.
KBOUTP
#define KBOUTP 0x60 /* kbd data port(O) */
Definition at line 54 of file pckbd.c.
KBR_ACK
#define KBR_ACK 0xFA /* received a valid command */
Definition at line 82 of file pckbd.c.
KBR_BREAK
#define KBR_BREAK 0xF0 /* break code prefix - sent on key release */
Definition at line 85 of file pckbd.c.
KBR_ECHO
#define KBR_ECHO 0xEE /* echo response */
Definition at line 87 of file pckbd.c.
KBR_EXTENDED
#define KBR_EXTENDED 0xE0 /* extended key sequence */
Definition at line 80 of file pckbd.c.
KBR_FAILURE
#define KBR_FAILURE 0xFD /* diagnosic failure */
Definition at line 84 of file pckbd.c.
KBR_OVERRUN
#define KBR_OVERRUN 0x00 /* flooded */
Definition at line 83 of file pckbd.c.
KBR_RESEND
#define KBR_RESEND 0xFE /* needs resend of command */
Definition at line 81 of file pckbd.c.
KBR_RSTDONE
#define KBR_RSTDONE 0xAA /* reset complete */
Definition at line 86 of file pckbd.c.
KBS_DIB
#define KBS_DIB 0x01 /* kbd data in buffer */
Definition at line 26 of file pckbd.c.
KBS_IBF
#define KBS_IBF 0x02 /* kbd input buffer low */
Definition at line 27 of file pckbd.c.
KBS_NOSEC
#define KBS_NOSEC 0x10 /* kbd security lock not engaged */
Definition at line 30 of file pckbd.c.
KBS_OCMD
#define KBS_OCMD 0x08 /* kbd output buffer has command */
Definition at line 29 of file pckbd.c.
KBS_PERR
#define KBS_PERR 0x80 /* kbd parity error */
Definition at line 33 of file pckbd.c.
KBS_RERR
#define KBS_RERR 0x40 /* kbd receive error */
Definition at line 32 of file pckbd.c.
KBS_TERR
#define KBS_TERR 0x20 /* kbd transmission error or from mouse */
Definition at line 31 of file pckbd.c.
KBS_WARM
#define KBS_WARM 0x04 /* kbd input buffer low */
Definition at line 28 of file pckbd.c.
KBSTATP
#define KBSTATP 0x64 /* kbd controller status port(I) */
Definition at line 25 of file pckbd.c.
KC8_CPU
#define KC8_CPU 0x04 /* exit from protected mode reset */
Definition at line 63 of file pckbd.c.
KC8_IGNSEC
#define KC8_IGNSEC 0x08 /* ignore security lock */
Definition at line 62 of file pckbd.c.
KC8_KDISABLE
#define KC8_KDISABLE 0x10 /* disable keyboard */
Definition at line 61 of file pckbd.c.
KC8_KENABLE
#define KC8_KENABLE 0x01 /* enable keyboard interrupt */
Definition at line 65 of file pckbd.c.
KC8_MDISABLE
#define KC8_MDISABLE 0x20 /* disable mouse */
Definition at line 60 of file pckbd.c.
KC8_MENABLE
#define KC8_MENABLE 0x02 /* enable mouse interrupt */
Definition at line 64 of file pckbd.c.
KC8_TRANS
#define KC8_TRANS 0x40 /* convert to old scan codes */
Definition at line 59 of file pckbd.c.
KEY_DEL
#define KEY_DEL 0xE9
Definition at line 20 of file pckbd.c.
KEY_DN
#define KEY_DN 0xE3
Definition at line 14 of file pckbd.c.
KEY_END
#define KEY_END 0xE1
Definition at line 12 of file pckbd.c.
KEY_HOME
#define KEY_HOME 0xE0
Definition at line 11 of file pckbd.c.
KEY_INS
#define KEY_INS 0xE8
Definition at line 19 of file pckbd.c.
KEY_LF
#define KEY_LF 0xE4
Definition at line 15 of file pckbd.c.
KEY_PGDN
#define KEY_PGDN 0xE7
Definition at line 18 of file pckbd.c.
KEY_PGUP
#define KEY_PGUP 0xE6
Definition at line 17 of file pckbd.c.
KEY_RT
#define KEY_RT 0xE5
Definition at line 16 of file pckbd.c.
KEY_UP
#define KEY_UP 0xE2
Definition at line 13 of file pckbd.c.
NO
#define NO 0
Definition at line 94 of file pckbd.c.
NUMLOCK
#define NUMLOCK (1<<4)
Definition at line 101 of file pckbd.c.
SCROLLLOCK
#define SCROLLLOCK (1<<5)
Definition at line 102 of file pckbd.c.
SHIFT
#define SHIFT (1<<0)
Definition at line 96 of file pckbd.c.
Function Documentation
_kbdProcessData()
static int _kbdProcessData (void) static
Definition at line 199 of file pckbd.c.
{
     // Adopted from JOS/xv6
     int c;
     uint8_t stat, data;
     static uint32_t shift;
     // Read keyboard status
     stat = inb(KBSTATP);
     // Read data in keyboard buffer
     if ((stat & KBS_DIB) == 0)
         return -1;
     // Ignore data from mouse.
     if (stat & KBS_TERR)
         return -1;
     // Read keyboard data
     data = inb(KBDATAP);
     if (data == 0xE0) {
         // E0 escape character
         shift |= E0ESC;
         return 0;
     } else if (data & 0x80) {
         // Key released
         data = (shift & E0ESC ? data : data & 0x7F);
         shift &= ~(shiftcode[data] | E0ESC);
         return 0;
     } else if (shift & E0ESC) {
         // Last character was an E0 escape; or with 0x80
         data |= 0x80;
         shift &= ~E0ESC;
     }
     shift |= shiftcode[data];
     shift ^= togglecode[data];
     c = charcode[shift & (CTL | SHIFT)][data];
     if (shift & CAPSLOCK) {
         if ('a' <= c && c <= 'z')
             c += 'A' - 'a';
         else if ('A' <= c && c <= 'Z')
             c += 'a' - 'A';
     }
     // Process special keys
     // Ctrl-Alt-Del: reboot
     if (!(~shift & (CTL | ALT)) && c == KEY_DEL) {
         consoleErrPrintC("Rebooting!\n");
         outb(0x92, 0x3); // courtesy of Chris Frost
     }
     return c;
 }
Referenced by kbdInit(), and kbdIntr().
kbdGetNextChar()
int kbdGetNextChar (void)
Definition at line 276 of file pckbd.c.
{
     int c;
     kbdIntr();
     if (kbdBuffer.writePos != kbdBuffer.readPos) {
         c = kbdBuffer.buffer[kbdBuffer.readPos];
         kbdBuffer.readPos = (kbdBuffer.readPos + 1) % KBD_BUF_SIZE;
         return c;
     }
     // No new char from keyboard
     return 0;
 }
kbdInit()
void kbdInit (void)
Definition at line 254 of file pckbd.c.
                    {
     kbdBuffer.readPos = 0;
     kbdBuffer.writePos = 0;
     consoleOutPrintC("Initializing keyboard...");
     // Try to read a char
     _kbdProcessData();
     consoleOutPrintC("%<Done\n", WHITE);
 }
kbdIntr()
static void kbdIntr (void) static
Definition at line 264 of file pckbd.c.
{
     int c;
     while (true) {
         c = _kbdProcessData();
         if (c == -1) return;
         else if (c == 0) continue;
         kbdBuffer.buffer[kbdBuffer.writePos] = c;
         kbdBuffer.writePos = (kbdBuffer.writePos + 1) % KBD_BUF_SIZE;
     }
 }
Referenced by kbdGetNextChar().
Variable Documentation
buffer
uint8_t buffer[KBD_BUF_SIZE]
Definition at line 193 of file pckbd.c.
charcode
uint8_t* charcode[4]
Initial value:
= {
        normalmap,
        shiftmap,
        ctlmap,
        ctlmap
}
Definition at line 184 of file pckbd.c.
Referenced by _kbdProcessData().
ctlmap
uint8_t ctlmap[256]
Initial value:
=
        {
                NO,      NO,      NO,      NO,      NO,      NO,      NO,      NO,
                NO,      NO,      NO,      NO,      NO,      NO,      NO,      NO,
                C('Q'),  C('W'),  C('E'),  C('R'),  C('T'),  C('Y'),  C('U'),  C('I'),
                C('O'),  C('P'),  NO,      NO,      '\r',    NO,      C('A'),  C('S'),
                C('D'),  C('F'),  C('G'),  C('H'),  C('J'),  C('K'),  C('L'),  NO,
                NO,      NO,      NO,      C('\\'), C('Z'),  C('X'),  C('C'),  C('V'),
                C('B'),  C('N'),  C('M'),  NO,      NO,      C('/'),  NO,      NO,
                [0x97] = KEY_HOME,
                [0xB5] = C('/'),        [0xC8] = KEY_UP,
                [0xC9] = KEY_PGUP,      [0xCB] = KEY_LF,
                [0xCD] = KEY_RT,        [0xCF] = KEY_END,
                [0xD0] = KEY_DN,        [0xD1] = KEY_PGDN,
                [0xD2] = KEY_INS,       [0xD3] = KEY_DEL
        }
Definition at line 167 of file pckbd.c.
kbdBuffer
struct { ... } kbdBuffer
Referenced by kbdGetNextChar(), kbdInit(), and kbdIntr().
normalmap
uint8_t normalmap[256]
Initial value:
=
        {
                NO,   0x1B, '1',  '2',  '3',  '4',  '5',  '6',
                '7',  '8',  '9',  '0',  '-',  '=',  '\b', '\t',
                'q',  'w',  'e',  'r',  't',  'y',  'u',  'i',
                'o',  'p',  '[',  ']',  '\n', NO,   'a',  's',
                'd',  'f',  'g',  'h',  'j',  'k',  'l',  ';',
                '\'', '`',  NO,   '\\', 'z',  'x',  'c',  'v',
                'b',  'n',  'm',  ',',  '.',  '/',  NO,   '*',
                NO,   ' ',  NO,   NO,   NO,   NO,   NO,   NO,
                NO,   NO,   NO,   NO,   NO,   NO,   NO,   '7',
                '8',  '9',  '-',  '4',  '5',  '6',  '+',  '1',
                '2',  '3',  '0',  '.',  NO,   NO,   NO,   NO,
                [0xC7] = KEY_HOME,        [0x9C] = '\n' ,
                [0xB5] = '/' ,      [0xC8] = KEY_UP,
                [0xC9] = KEY_PGUP,        [0xCB] = KEY_LF,
                [0xCD] = KEY_RT,          [0xCF] = KEY_END,
                [0xD0] = KEY_DN,          [0xD1] = KEY_PGDN,
                [0xD2] = KEY_INS,         [0xD3] = KEY_DEL
        }
Definition at line 123 of file pckbd.c.
readPos
uint32_t readPos
Definition at line 194 of file pckbd.c.
shiftcode
uint8_t shiftcode[256]
Initial value:
=
        {
                [0x1D] = CTL,
                [0x2A] = SHIFT,
                [0x36] = SHIFT,
                [0x38] = ALT,
                [0x9D] = CTL,
                [0xB8] = ALT
        }
Definition at line 106 of file pckbd.c.
Referenced by _kbdProcessData().
shiftmap
uint8_t shiftmap[256]
Initial value:
=
        {
                NO,   033,  '!',  '@',  '#',  '$',  '%',  '^',
                '&',  '*',  '(',  ')',  '_',  '+',  '\b', '\t',
                'Q',  'W',  'E',  'R',  'T',  'Y',  'U',  'I',
                'O',  'P',  '{',  '}',  '\n', NO,   'A',  'S',
                'D',  'F',  'G',  'H',  'J',  'K',  'L',  ':',
                '"',  '~',  NO,   '|',  'Z',  'X',  'C',  'V',
                'B',  'N',  'M',  '<',  '>',  '?',  NO,   '*',
                NO,   ' ',  NO,   NO,   NO,   NO,   NO,   NO,
                NO,   NO,   NO,   NO,   NO,   NO,   NO,   '7',
                '8',  '9',  '-',  '4',  '5',  '6',  '+',  '1',
                '2',  '3',  '0',  '.',  NO,   NO,   NO,   NO,
                [0xC7] = KEY_HOME,        [0x9C] = '\n' ,
                [0xB5] = '/' ,      [0xC8] = KEY_UP,
                [0xC9] = KEY_PGUP,        [0xCB] = KEY_LF,
                [0xCD] = KEY_RT,          [0xCF] = KEY_END,
                [0xD0] = KEY_DN,          [0xD1] = KEY_PGDN,
                [0xD2] = KEY_INS,         [0xD3] = KEY_DEL
        }
Definition at line 144 of file pckbd.c.
togglecode
uint8_t togglecode[256]
Initial value:
=
        {
                [0x3A] = CAPSLOCK,
                [0x45] = NUMLOCK,
                [0x46] = SCROLLLOCK
        }
Definition at line 116 of file pckbd.c.
Referenced by _kbdProcessData().
writePos
uint32_t writePos
Definition at line 195 of file pckbd.c.