Litchi: printfmt.cc File Reference
printfmt.cc File Reference
#include <include/stdio.hh>
#include <include/ctype.h>
#include <include/string.hh>
#include <include/color.h>
#include <include/result.hh>
Namespaces
console
console::ge
Macros
#define putColorChar(c, fore, back) do { putChar(COLOR_CHAR(c, fore, back)); } while (0)
Functions
static long long _getIntVa (va_list *ap, int longFlag)
static unsigned long long _getUIntVa (va_list *ap, int longFlag)
static constexpr const char * describe (Result result)
void console::ge::printFmt (PutCharFunc putChar, const char *fmt,...)
void console::ge::printFmtVa (PutCharFunc putChar, const char *fmt, va_list ap, enum color_t defFore, enum color_t defBack)
void console::ge::printNumber (PutCharFunc putChar, unsigned long long num, unsigned base, int width, int paddingChar, bool capital, enum color_t fore, enum color_t back)
Variables
constexpr char NULL_FMT [] = "(null)"
Macro Definition Documentation
putColorChar
#define putColorChar (c, fore, back) do { putChar(COLOR_CHAR(c, fore, back)); } while (0)
Function Documentation
_getIntVa()
static long long _getIntVa (va_list * ap, int longFlag) static
Definition at line 51 of file printfmt.cc.
{
     unsigned long long num;
     if (longFlag == 0) num = va_arg(*ap, int);
     else if (longFlag == 1) num = va_arg(*ap, long);
     else num = va_arg(*ap, long long);
     return num;
 }
Referenced by console::ge::printFmtVa().
_getUIntVa()
static unsigned long long _getUIntVa (va_list * ap, int longFlag) static
Definition at line 40 of file printfmt.cc.
{
     unsigned long long num;
     if (longFlag == 0) num = va_arg(*ap, unsigned int);
     else if (longFlag == 1) num = va_arg(*ap, unsigned long);
     else num = va_arg(*ap, unsigned long long);
     return num;
 }
Referenced by console::ge::printFmtVa().
describe()
static constexpr const char* describe (Result result) inline static constexpr
Definition at line 11 of file printfmt.cc.
{
     switch (result) {
         case Result::ok:
             return "OK";
         case Result::unknownError:
             return "Unknown Error";
         case Result::invalidArg:
             return "Invalid Argument";
         case Result::noMemory:
             return "No Memory";
         case Result::noFreeTask:
             return "No Free Task";
         case Result::fuck:
             return "Fucking Error";
         case Result::tooManyArgs:
             return "Too Many Arguments";
         case Result::badSyntax:
             return "Bad Syntax";
         case Result::badCommand:
             return "Bad Command";
         case Result::noSuchTask:
             return "No Such Task";
     }
     return "Undefined Error";
 }
Referenced by trap::Frame::dispatch(), console::ge::printFmtVa(), and trap::trap().
Variable Documentation
NULL_FMT
constexpr char NULL_FMT[] = "(null)" constexpr
Definition at line 37 of file printfmt.cc.
Referenced by console::ge::printFmtVa().