Litchi: stdlib.hh File Reference
stdlib.hh File Reference
#include <include/types.h>
#include <include/syscall.hh>
#include <include/trap.hh>
Functions
static int32_t syscall (ksyscall::Num type, uint32_t a1=0, uint32_t a2=0, uint32_t a3=0, uint32_t a4=0, uint32_t a5=0)
Function Documentation
syscall()
static int32_t syscall (ksyscall::Num type, uint32_t a1 = 0, uint32_t a2 = 0, uint32_t a3 = 0, uint32_t a4 = 0, uint32_t a5 = 0) inline static
Definition at line 12 of file stdlib.hh.
{
     int32_t ret;
     // move type into: eax
     // move arguments into: edx, ecx, ebx, edi, esi
     asm volatile("int %1\n"
     : "=a" (ret)
     : "i" (trap::Type::syscall),
     "a" (type),
     "d" (a1),
     "c" (a2),
     "b" (a3),
     "D" (a4),
     "S" (a5)
     : "cc", "memory");
     return ret;
 }
Referenced by trap::Frame::dispatch(), trap::init(), pageFault4(), trap::trap(), and umain().