Litchi: task::Task Struct Reference
task::Task Struct Reference
#include <task.hh>
Public Member Functions
void destroy (bool fromKernel)
void free ()
void run (bool verbose)
Static Public Member Functions
static std::tuple< Task *, Result > alloc (taskid_t parentId)
static std::tuple< Task *, Result > create (uint8_t *binary, TaskType type, const char *_name="<unknown>")
Public Attributes
taskid_t id
char name [nameLength]
Task * nextFree
pde_t * pageDir
taskid_t parentId
TaskStatus status
trap::Frame trapFrame
TaskType type
Static Public Attributes
static Task * array = nullptr
static Task * current = nullptr
static Task * freeList = nullptr
static constexpr size_t maxCount = 0x100
static constexpr size_t nameLength = 32
Private Member Functions
void loadElf (uint8_t *binary)
void regionAlloc (void *va, size_t len)
Result setupMemory ()
Detailed Description
Definition at line 16 of file kernel/task.hh.
Member Function Documentation
alloc()
std::tuple< Task *, Result > task::Task::alloc (taskid_t parentId) static
Definition at line 73 of file task.cc.
{
         // find a free slot
         Task *task = freeList;
         if (task == nullptr)
             return {nullptr, Result::noFreeTask};
         freeList = task->nextFree;
         // allocate page dir
         if (Result r; (r = task->setupMemory()) != Result::ok)
             return {nullptr, r};
         // allocate a random id, ending up with the #
         uint32_t rand = lrandom::rand() << 16 | lrandom::rand();
         task->id = (rand & ~(maxCount - 1)) | (task - array);
         // set other fields
         task->parentId = parentId;
         task->status = TaskStatus::ready;
         task->type = TaskType::user;
         // clear the trap frame
         task->trapFrame.clear();
         // set segment descriptors to users', 3: RPL, see: initPerCpu()
         task->trapFrame.ds = GD_UD | 3;
         task->trapFrame.es = GD_UD | 3;
         task->trapFrame.cs = GD_UT | 3;
         task->trapFrame.ss = GD_UD | 3;
         // set user stack
         task->trapFrame.esp = USTACKTOP; // user stack top
         // eip will be set after binary loaded
         print("[%08x] Allocated task\n", task->id);
         return {task, Result::ok};
     }
create()
std::tuple< Task *, Result > task::Task::create (uint8_t * binary, TaskType type, const char * _name = "<unknown>") static
Definition at line 205 of file task.cc.
{
         // allocate a free task
         auto[task, r] = alloc(0);
         if (r != Result::ok) return {nullptr, r};
         // set up vm
         r = task->setupMemory();
         if (r != Result::ok) return {nullptr, r};
         // load elf
         task->loadElf(binary);
         str::copy(task->name, _name, nameLength);
         print("[%08x] Created task %<'%s'\n", task->id, WHITE, task->name);
         return {task, Result::ok};
     }
destroy()
void task::Task::destroy (bool fromKernel)
Definition at line 235 of file task.cc.
{
         print("%<[%08x] Destroyed by %s\n", WHITE, id, fromKernel ? "kernel" : "user");
         if (this == current) {
             current = nullptr;
             x86::lcr3(PHY_ADDR(vmem::kernelPageDir));
         }
         this->free();
         monitor::main();
     }
Referenced by ksyscall::exit(), trap::handler::pageFault(), and ksyscall::putString().
free()
void task::Task::free ()
Definition at line 125 of file task.cc.
                     {
         if (this == current) x86::lcr3(PHY_ADDR(vmem::kernelPageDir));
         // free all pages, from 0x0 to UTOP
         for (int pdx = 0; pdx < (int) PDX(UTOP); ++pdx) {
             auto pde = this->pageDir[pdx];  // find the page dir entry
             if (!(pde & PTE_P)) continue;   // page table not present
             auto pa = PTE_ADDR(pde);
             auto pageTable = static_cast<pte_t *>(KERN_ADDR(pa));
             for (int ptx = 0; ptx < NPTENTRIES; ++ptx) {
                 auto pte = pageTable[ptx];  // find the page table entry
                 if (pte & PTE_P) // remove the page from page dir, and free the info if needed
                     vmem::pgdir::remove(this->pageDir, PGADDR(pdx, ptx, 0));
             }
             // free the page table itself
             pageDir[pdx] = 0;
             vmem::PageInfo::fromPhy(pa)->decRef();
         }
         // free the page dir itself
         vmem::PageInfo::fromPhy(PHY_ADDR(pageDir))->decRef();
         // free the Task
         status = TaskStatus::free;
         nextFree = freeList;
         freeList = this;
         print("[%08x] Freed task\n", this->id);
     }
loadElf()
void task::Task::loadElf (uint8_t * binary) private
Definition at line 157 of file task.cc.
{
         auto elf = (Elf *) binary;
         if (elf->e_magic != ELF_MAGIC)
             kernelPanic("bad elf binary");
         x86::lcr3(PHY_ADDR(this->pageDir));
         // copy the binary
         auto ph = (Proghdr *) (binary + elf->e_phoff);  // find the elf header
         auto eph = ph + elf->e_phnum;                   // end of the header
         for (; ph < eph; ++ph) {
             if (ph->p_type != ELF_PROG_LOAD || ph->p_memsz == 0) continue;  // not to load
             // allocate pages
             this->regionAlloc((void *) ph->p_va, ph->p_memsz);
             // copy text/data, only copy filesz length
             auto va = binary + ph->p_offset;
 //            print("VA %p\n", va);
             mem::copy((void *) ph->p_va, va, ph->p_filesz);
         }
         x86::lcr3(PHY_ADDR(vmem::kernelPageDir));
         // allocate stack (PGSIZE)
         this->regionAlloc((void *) (USTACKTOP - PGSIZE), PGSIZE);
         // set eip to elf entry point
         this->trapFrame.eip = elf->e_entry;
         print("[%08x] Loaded elf\n", this->id);
     }
regionAlloc()
void task::Task::regionAlloc (void * va, size_t len) private
Definition at line 189 of file task.cc.
{
         char *va = static_cast<char *>(_va);
         auto vaLo = ROUNDDOWN(va, PGSIZE);
         auto vaHi = ROUNDUP(va + len, PGSIZE);
         if (vaLo >= vaHi) kernelPanic("bad va");
         // allocate pages
         for (auto vaIt = vaLo; vaIt < vaHi; vaIt += PGSIZE) {
             auto page = vmem::PageInfo::alloc(true);
             if (page == nullptr) kernelPanic("out of memory");
 //            print("PA %p\n", page->toPhy());
             auto result = vmem::pgdir::insert(this->pageDir, page, vaIt, PTE_U | PTE_W);
             if (result != Result::ok) kernelPanic("insert page failed");
         }
     }
run()
void task::Task::run (bool verbose)
Definition at line 220 of file task.cc.
{
         if (this != current) {
             // context switching
             if (current != nullptr && current->status == TaskStatus::running)
                 current->status = TaskStatus::ready;
             this->status = TaskStatus::running;
             current = this;
             x86::lcr3(PHY_ADDR(this->pageDir));
         }
         if (verbose) print("[%08x] Goodbye, kernel!\n", id);
         this->trapFrame.pop();
     }
setupMemory()
Result task::Task::setupMemory () private
Definition at line 109 of file task.cc.
{
         // allocate a page for the task's page dir
         auto page = vmem::PageInfo::alloc(true);
         if (page == nullptr) return Result::noMemory;
         // simply duplicate the kernel's
         this->pageDir = static_cast<pde_t *>(page->toKernV());
         mem::copy(page->toKernV(), vmem::kernelPageDir, PGSIZE);
         page->refCount += 1;
         // again, make a recursive map to the page dir itself
         this->pageDir[PDX(UVPT)] = PHY_ADDR(this->pageDir) | PTE_U | PTE_P;
         return Result::ok;
     }
Member Data Documentation
array
Task * task::Task::array = nullptr static
Definition at line 19 of file kernel/task.hh.
current
Task * task::Task::current = nullptr static
Definition at line 21 of file kernel/task.hh.
Referenced by trap::Frame::dispatch(), ksyscall::exit(), monitor::main(), trap::handler::pageFault(), and ksyscall::putString().
freeList
Task * task::Task::freeList = nullptr static
Definition at line 20 of file kernel/task.hh.
id
taskid_t task::Task::id
Definition at line 24 of file kernel/task.hh.
maxCount
constexpr size_t task::Task::maxCount = 0x100 static constexpr
Definition at line 17 of file kernel/task.hh.
name
char task::Task::name[nameLength]
Definition at line 26 of file kernel/task.hh.
nameLength
constexpr size_t task::Task::nameLength = 32 static constexpr
Definition at line 18 of file kernel/task.hh.
nextFree
Task* task::Task::nextFree
Definition at line 23 of file kernel/task.hh.
pageDir
pde_t* task::Task::pageDir
Definition at line 31 of file kernel/task.hh.
parentId
taskid_t task::Task::parentId
Definition at line 25 of file kernel/task.hh.
status
TaskStatus task::Task::status
Definition at line 27 of file kernel/task.hh.
trapFrame
trap::Frame task::Task::trapFrame
Definition at line 30 of file kernel/task.hh.
type
TaskType task::Task::type
Definition at line 28 of file kernel/task.hh.
The documentation for this struct was generated from the following files:
kernel/task.hh
task.cc