Litchi: vmem::PageInfo Struct Reference
vmem::PageInfo Struct Reference
#include <vmem.hh>
Public Member Functions
void decRef ()
void free ()
void * toKernV ()
physaddr_t toPhy ()
Static Public Member Functions
static PageInfo * alloc (bool zero)
static int freeCount ()
static PageInfo * fromPhy (physaddr_t pa)
Public Attributes
struct PageInfo * nextFree
uint16_t refCount
Static Public Attributes
static PageInfo * array = nullptr
static PageInfo * freeList = nullptr
Detailed Description
Definition at line 83 of file vmem.hh.
Member Function Documentation
alloc()
PageInfo * vmem::PageInfo::alloc (bool zero) static
Definition at line 43 of file vmem.cc.
{
         struct PageInfo *pp = PageInfo::freeList;
         if (pp == nullptr) {
             // Out of free memory
             return nullptr;
         }
         PageInfo::freeList = PageInfo::freeList->nextFree;
         pp->nextFree = nullptr;
         if (zero) {
             void *va = pp->toKernV();
             mem::clear(va, PGSIZE);
         }
         return pp;
     }
Referenced by vmem::pgdir::findPte(), vmem::pgdir::init(), task::Task::regionAlloc(), and task::Task::setupMemory().
decRef()
void vmem::PageInfo::decRef ()
Definition at line 31 of file vmem.cc.
{
         if (--refCount <= 0) this->free();
     }
Referenced by task::Task::free().
free()
void vmem::PageInfo::free ()
Definition at line 35 of file vmem.cc.
{
         if (refCount != 0 || nextFree != nullptr) {
             kernelPanic("pageFree: cannot free page #%d", this - PageInfo::array);
         }
         nextFree = PageInfo::freeList;
         PageInfo::freeList = this;
     }
Referenced by decRef().
freeCount()
int vmem::PageInfo::freeCount () static
Definition at line 58 of file vmem.cc.
{
         auto p = freeList;
         int count = 0;
         while (p) {
             count++;
             p = p->nextFree;
         }
         return count;
     }
Referenced by monitor::page().
fromPhy()
static PageInfo* vmem::PageInfo::fromPhy (physaddr_t pa) inline static
Definition at line 102 of file vmem.hh.
{
             if (PGNUM(pa) >= nPages || nPages == 0)
                 kernelPanic("phyToPage: cannot convert 0x%p to PageInfo", pa);
             return array + PGNUM(pa);
         }
Referenced by vmem::pgdir::findInfo(), task::Task::free(), vmem::page::init(), and vmem::utils::show().
toKernV()
void* vmem::PageInfo::toKernV () inline
Definition at line 98 of file vmem.hh.
{
             return KERN_ADDR(this->toPhy());
         }
Referenced by alloc(), vmem::pgdir::findPte(), and vmem::pgdir::init().
toPhy()
physaddr_t vmem::PageInfo::toPhy () inline
Definition at line 94 of file vmem.hh.
{
             return (this - array) << PGSHIFT;
         }
Referenced by vmem::pgdir::findPte(), vmem::pgdir::insert(), and toKernV().
Member Data Documentation
array
PageInfo * vmem::PageInfo::array = nullptr static
Definition at line 87 of file vmem.hh.
Referenced by fromPhy(), vmem::page::init(), vmem::pgdir::init(), and toPhy().
freeList
PageInfo * vmem::PageInfo::freeList = nullptr static
Definition at line 88 of file vmem.hh.
Referenced by alloc(), free(), freeCount(), and vmem::page::init().
nextFree
struct PageInfo* vmem::PageInfo::nextFree
Definition at line 84 of file vmem.hh.
Referenced by alloc(), free(), vmem::page::init(), and vmem::pgdir::init().
refCount
uint16_t vmem::PageInfo::refCount
Definition at line 85 of file vmem.hh.
Referenced by decRef(), vmem::pgdir::findPte(), free(), vmem::page::init(), vmem::pgdir::init(), and vmem::pgdir::insert().
The documentation for this struct was generated from the following files:
vmem.hh
vmem.cc