Litchi: x86.h File Reference
x86.h File Reference
#include <include/types.h>
Functions
static void breakpoint (void)
static void cpuid (uint32_t info, uint32_t *eaxp, uint32_t *ebxp, uint32_t *ecxp, uint32_t *edxp)
static uint8_t inb (int port)
static uint32_t inl (int port)
static void insb (int port, void *addr, int cnt)
static void insl (int port, void *addr, int cnt)
static void insw (int port, void *addr, int cnt)
static void invlpg (void *addr)
static uint16_t inw (int port)
static void lcr0 (uint32_t val)
static void lcr3 (uint32_t val)
static void lcr4 (uint32_t val)
static void lgdt (void *p)
static void lidt (void *p)
static void lldt (uint16_t sel)
static void ltr (uint16_t sel)
static void outb (int port, uint8_t data)
static void outl (int port, uint32_t data)
static void outsb (int port, const void *addr, int cnt)
static void outsl (int port, const void *addr, int cnt)
static void outsw (int port, const void *addr, int cnt)
static void outw (int port, uint16_t data)
static uint32_t rcr0 (void)
static uint32_t rcr2 (void)
static uint32_t rcr3 (void)
static uint32_t rcr4 (void)
static uint32_t rdrand ()
static uint32_t read_ebp (void)
static uint32_t read_eflags (void)
static uint32_t read_esp (void)
static uint64_t read_tsc (void)
static void tlbflush (void)
static void write_eflags (uint32_t eflags)
static uint32_t xchg (volatile uint32_t *addr, uint32_t newval)
Function Documentation
breakpoint()
static void breakpoint (void) inline static
Definition at line 12 of file x86.h.
     {
         asm volatile("int3");
     }
Referenced by trap::describe(), trap::Frame::dispatch(), and trap::init().
cpuid()
static void cpuid (uint32_t info, uint32_t * eaxp, uint32_t * ebxp, uint32_t * ecxp, uint32_t * edxp) inline static
Definition at line 232 of file x86.h.
     {
         uint32_t eax, ebx, ecx, edx;
         asm volatile("cpuid"
                  : "=a" (eax), "=b" (ebx), "=c" (ecx), "=d" (edx)
                  : "a" (info));
         if (eaxp)
             *eaxp = eax;
         if (ebxp)
             *ebxp = ebx;
         if (ecxp)
             *ecxp = ecx;
         if (edxp)
             *edxp = edx;
     }
inb()
static uint8_t inb (int port) inline static
Definition at line 18 of file x86.h.
     {
         uint8_t data;
         asm volatile("inb %w1,%0" : "=a" (data) : "d" (port));
         return data;
     }
Referenced by _kbdProcessData(), console::serial::delay(), console::serial::init(), console::cga::init(), nvram::mc146818_read(), and waitdisk().
inl()
static uint32_t inl (int port) inline static
Definition at line 52 of file x86.h.
     {
         uint32_t data;
         asm volatile("inl %w1,%0" : "=a" (data) : "d" (port));
         return data;
     }
insb()
static void insb (int port, void * addr, int cnt) inline static
Definition at line 26 of file x86.h.
     {
         asm volatile("cld\n\trepne\n\tinsb"
                  : "=D" (addr), "=c" (cnt)
                  : "d" (port), "0" (addr), "1" (cnt)
                  : "memory", "cc");
     }
insl()
static void insl (int port, void * addr, int cnt) inline static
Definition at line 60 of file x86.h.
     {
         asm volatile("cld\n\trepne\n\tinsl"
                  : "=D" (addr), "=c" (cnt)
                  : "d" (port), "0" (addr), "1" (cnt)
                  : "memory", "cc");
     }
Referenced by readsect().
insw()
static void insw (int port, void * addr, int cnt) inline static
Definition at line 43 of file x86.h.
     {
         asm volatile("cld\n\trepne\n\tinsw"
                  : "=D" (addr), "=c" (cnt)
                  : "d" (port), "0" (addr), "1" (cnt)
                  : "memory", "cc");
     }
invlpg()
static void invlpg (void * addr) inline static
Definition at line 114 of file x86.h.
     {
         asm volatile("invlpg (%0)" : : "r" (addr) : "memory");
     }
Referenced by vmem::pgdir::invalidateTLB().
inw()
static uint16_t inw (int port) inline static
Definition at line 35 of file x86.h.
     {
         uint16_t data;
         asm volatile("inw %w1,%0" : "=a" (data) : "d" (port));
         return data;
     }
lcr0()
static void lcr0 (uint32_t val) inline static
Definition at line 144 of file x86.h.
     {
         asm volatile("movl %0,%%cr0" : : "r" (val));
     }
Referenced by vmem::pgdir::init().
lcr3()
static void lcr3 (uint32_t val) inline static
Definition at line 166 of file x86.h.
     {
         asm volatile("movl %0,%%cr3" : : "r" (val));
     }
Referenced by task::Task::destroy(), task::Task::free(), vmem::pgdir::init(), task::Task::loadElf(), and task::Task::run().
lcr4()
static void lcr4 (uint32_t val) inline static
Definition at line 180 of file x86.h.
     {
         asm volatile("movl %0,%%cr4" : : "r" (val));
     }
lgdt()
static void lgdt (void * p) inline static
Definition at line 126 of file x86.h.
     {
         asm volatile("lgdt (%0)" : : "r" (p));
     }
Referenced by task::initPerCpu().
lidt()
static void lidt (void * p) inline static
Definition at line 120 of file x86.h.
     {
         asm volatile("lidt (%0)" : : "r" (p));
     }
Referenced by trap::initPerCpu().
lldt()
static void lldt (uint16_t sel) inline static
Definition at line 132 of file x86.h.
     {
         asm volatile("lldt %0" : : "r" (sel));
     }
ltr()
static void ltr (uint16_t sel) inline static
Definition at line 138 of file x86.h.
     {
         asm volatile("ltr %0" : : "r" (sel));
     }
Referenced by trap::initPerCpu().
outb()
static void outb (int port, uint8_t data) inline static
Definition at line 69 of file x86.h.
     {
         asm volatile("outb %0,%w1" : : "a" (data), "d" (port));
     }
Referenced by _kbdProcessData(), console::cga::cursorRefresh(), console::serial::init(), console::cga::init(), nvram::mc146818_read(), readsect(), sys::reboot(), console::serial::sout(), and mp::lapic::startAP().
outl()
static void outl (int port, uint32_t data) inline static
Definition at line 108 of file x86.h.
     {
         asm volatile("outl %0,%w1" : : "a" (data), "d" (port));
     }
outsb()
static void outsb (int port, const void * addr, int cnt) inline static
Definition at line 75 of file x86.h.
     {
         asm volatile("cld\n\trepne\n\toutsb"
                  : "=S" (addr), "=c" (cnt)
                  : "d" (port), "0" (addr), "1" (cnt)
                  : "cc");
     }
outsl()
static void outsl (int port, const void * addr, int cnt) inline static
Definition at line 99 of file x86.h.
     {
         asm volatile("cld\n\trepne\n\toutsl"
                  : "=S" (addr), "=c" (cnt)
                  : "d" (port), "0" (addr), "1" (cnt)
                  : "cc");
     }
outsw()
static void outsw (int port, const void * addr, int cnt) inline static
Definition at line 90 of file x86.h.
     {
         asm volatile("cld\n\trepne\n\toutsw"
                  : "=S" (addr), "=c" (cnt)
                  : "d" (port), "0" (addr), "1" (cnt)
                  : "cc");
     }
outw()
static void outw (int port, uint16_t data) inline static
Definition at line 84 of file x86.h.
     {
         asm volatile("outw %0,%w1" : : "a" (data), "d" (port));
     }
Referenced by bootmain(), and sys::shutdown().
rcr0()
static uint32_t rcr0 (void) inline static
Definition at line 150 of file x86.h.
     {
         uint32_t val;
         asm volatile("movl %%cr0,%0" : "=r" (val));
         return val;
     }
Referenced by vmem::pgdir::init().
rcr2()
static uint32_t rcr2 (void) inline static
Definition at line 158 of file x86.h.
     {
         uint32_t val;
         asm volatile("movl %%cr2,%0" : "=r" (val));
         return val;
     }
Referenced by trap::handler::pageFault().
rcr3()
static uint32_t rcr3 (void) inline static
Definition at line 172 of file x86.h.
     {
         uint32_t val;
         asm volatile("movl %%cr3,%0" : "=r" (val));
         return val;
     }
rcr4()
static uint32_t rcr4 (void) inline static
Definition at line 186 of file x86.h.
     {
         uint32_t cr4;
         asm volatile("movl %%cr4,%0" : "=r" (cr4));
         return cr4;
     }
rdrand()
static uint32_t rdrand () inline static
Definition at line 269 of file x86.h.
{
         // only supported on newer x86 CPUs
         uint32_t r;
         asm volatile ("rdrand %%eax":"=a"(r));
         return r;
     }
read_ebp()
static uint32_t read_ebp (void) inline static
Definition at line 216 of file x86.h.
     {
         uint32_t ebp;
         asm volatile("movl %%ebp,%0" : "=r" (ebp));
         return ebp;
     }
Referenced by kdebug::backtrace().
read_eflags()
static uint32_t read_eflags (void) inline static
Definition at line 202 of file x86.h.
     {
         uint32_t eflags;
         asm volatile("pushfl; popl %0" : "=r" (eflags));
         return eflags;
     }
Referenced by trap::trap().
read_esp()
static uint32_t read_esp (void) inline static
Definition at line 224 of file x86.h.
     {
         uint32_t esp;
         asm volatile("movl %%esp,%0" : "=r" (esp));
         return esp;
     }
read_tsc()
static uint64_t read_tsc (void) inline static
Definition at line 249 of file x86.h.
     {
         uint64_t tsc;
         asm volatile("rdtsc" : "=A" (tsc));
         return tsc;
     }
tlbflush()
static void tlbflush (void) inline static
Definition at line 194 of file x86.h.
     {
         uint32_t cr3;
         asm volatile("movl %%cr3,%0" : "=r" (cr3));
         asm volatile("movl %0,%%cr3" : : "r" (cr3));
     }
write_eflags()
static void write_eflags (uint32_t eflags) inline static
Definition at line 210 of file x86.h.
     {
         asm volatile("pushl %0; popfl" : : "r" (eflags));
     }
xchg()
static uint32_t xchg (volatile uint32_t * addr, uint32_t newval) inline static
Definition at line 257 of file x86.h.
     {
         uint32_t result;
         // The + in "+m" denotes a read-modify-write operand.
         asm volatile("lock; xchgl %0, %1"
                  : "+m" (*addr), "=a" (result)
                  : "1" (newval)
                  : "cc");
         return result;
     }