name: Generate docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Brew Tap
      run: brew tap bugenzhao/litchi
    - name: Install Toolchains
      run: brew install i386-litchi-elf-binutils i386-litchi-elf-gcc
    - name: Install doxygen
      run: brew install doxygen graphviz
    - name: Build doc
      run: mkdir build && cd build && cmake .. && make doc
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
